In [18]:
import pandas as pd 
import numpy as np
import pickle as pk 
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix, brier_score_loss
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

pd.options.display.max_columns = 100
pd.options.display.max_rows = 60

# Preface: Evaluating Fairness Metrics on an eICU Prediction Task
In this notebook, you will:
1. Train a simple prediction model on real-world ICU data
2. Evaluate the model using several common algorithmic fairness metrics
3. Understand the equations behind these metrics
4. Reflect on when each fairness notion may or may not make sense in healthcare


In machine learning, people often talk about building a "fair" model. We will see in this notebook that fairness has been traditionally viewed as a single metric.

In this notebook, we will build intution for the fact that:
- a model can look fair under one metric and unfair under another
- fairness depends on the clinical context and is not straightforward / one-size-fits-all


---

# Load the data

In this notebook, our task will be to predict Y= `mortality_48h`. 
That is, using data from the first 24 hours of hospitalization, predict whether the patient will die within 48 hours.
However, at the end you will change the target variable and reconsider fairness for this context.

In [21]:
patient_agg = pd.read_parquet('../../X/clean_dataset.parquet')
feature_sets = pk.load(open('../../data/feature_names.pkl','rb'))
patient_agg

,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,hospitaldischargeyear,mortality_at48h,hospital_numbedscategory,hospital_region,"admissiondx_ARDS-adult respiratory distress syndrome, non-cardiogenic pulmonary edema",admissiondx_Abdomen only trauma,admissiondx_Abdomen/extremity trauma,admissiondx_Abdomen/face trauma,admissiondx_Abdomen/multiple trauma,admissiondx_Abdomen/pelvis trauma,admissiondx_Abdomen/spinal trauma,admissiondx_Ablation or mapping of cardiac conduction pathway,"admissiondx_Abscess, neurologic","admissiondx_Abscess/infection-cranial, surgery for",admissiondx_Acid-base/electrolyte disturbance,admissiondx_Addisons disease,admissiondx_Adrenal neoplasm (including pheochromocytoma),admissiondx_Adrenalectomy,admissiondx_Alcohol withdrawal,admissiondx_Amputation (non-traumatic),admissiondx_Amyotrophic lateral sclerosis,admissiondx_Anaphylaxis,"admissiondx_Anastomosis, vascular",admissiondx_Anemia,"admissiondx_Aneurysm repair, ventricular","admissiondx_Aneurysm, abdominal aortic","admissiondx_Aneurysm, abdominal aortic; with dissection","admissiondx_Aneurysm, abdominal aortic; with rupture","admissiondx_Aneurysm, dissecting aortic","admissiondx_Aneurysm, thoracic aortic","admissiondx_Aneurysm, thoracic aortic; with dissection","admissiondx_Aneurysm, thoracic aortic; with rupture","admissiondx_Aneurysm/pseudoaneurysm, other","admissiondx_Aneurysms, repair of other (except ventricular)","admissiondx_Angina, stable (asymp or stable pattern of symptoms w/meds)","admissiondx_Angina, unstable (angina interferes w/quality of life or meds are tolerated poorly)",admissiondx_Aortic and Mitral valve replacement,admissiondx_Aortic valve replacement (isolated),"admissiondx_Apnea, sleep","admissiondx_Apnea-sleep; surgery for (i.e., UPPP - uvulopalatopharyngoplasty)",admissiondx_Appendectomy,"admissiondx_Arrest, respiratory (without cardiac arrest)","admissiondx_Arteriovenous malformation, surgery for","admissiondx_Arthritis, rheumatoid","admissiondx_Arthritis, septic",...,calcium,cd 4,chloride,cortisol,creatinine,direct bilirubin,eos,ethanol,fibrinogen,folate,free T4,glucose,glucose CSF,haptoglobin,ionized calcium,lactate,lipase,lymphs,magnesium,monos,myoglobin,pH,paCO2,paO2,phosphate,platelets x 1000,polys,potassium,prealbumin,prolactin,protein CSF,protein C,protein S,reticulocyte count,salicylate,serum ketones,serum osmolality,sodium,total bilirubin,total cholesterol,total protein,transferrin,triglycerides,troponin I,troponin T,uric acid,urinary creatinine,urinary osmolality,urinary sodium,urinary specific gravity
0,128919,Female,70,Caucasian,59,2015,1,<100,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,9.000000,NaN,101.500000,NaN,2.125000,NaN,0.500000,NaN,NaN,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,12.500000,NaN,16.500000,NaN,NaN,NaN,NaN,NaN,211.000000,70.5,4.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.000000,3.35,NaN,7.10,NaN,NaN,NaN,NaN,8.1,NaN,NaN,NaN,NaN
1,128927,Female,52,Caucasian,60,2015,0,<100,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,8.100000,NaN,107.750000,NaN,0.700000,NaN,3.000000,234.0,NaN,NaN,NaN,74.5,NaN,NaN,NaN,NaN,NaN,45.000000,1.900,7.000000,NaN,NaN,NaN,NaN,NaN,273.000000,45.0,3.750000,NaN,NaN,NaN,NaN,NaN,NaN,2.3,NaN,NaN,144.500000,0.40,NaN,7.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,128941,Male,68,Caucasian,73,2015,0,>= 500,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,9.200000,NaN,103.500000,NaN,2.725000,0.1,0.500000,NaN,NaN,NaN,NaN,151.5,NaN,NaN,NaN,1.666667,NaN,3.500000,1.200,4.500000,NaN,NaN,NaN,NaN,NaN,265.500000,91.5,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.500000,0.40,NaN,7.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.018
3,128943,Male,71,Caucasian,67,2015,0,None,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,9.000000,NaN,98.000000,NaN,0.865000,NaN,0.000000,NaN,NaN,NaN,NaN,153.0,NaN,NaN,NaN,0.800000,NaN,3.000000,NaN,4.500000,NaN,7.43000,45.0,70.000,NaN,521.000000,92.5,4.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.000000,0.30,NaN,7.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,128948,Female,77,Caucasian,66,2014,0,100 - 249,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...,8.366667,NaN,104.666667,NaN,0.426667,NaN,0.000000,NaN,NaN,4.1,NaN,130.0,NaN,NaN,NaN,3.500000,NaN,16.333333,1.550,5.666667,NaN,7.45000,37.0,51.000,NaN,473.666667,78.0,3.833333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.333333,0.40,NaN,6.00,NaN,NaN,0.020000,NaN,NaN,NaN,NaN,NaN,1.026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135773,2743084,Male,50,Caucasian,458,2014,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,9.400000,NaN,109.000000,NaN,1.040000,NaN,1.000000,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,11.000000,NaN,NaN,NaN,NaN,NaN,133.000000,NaN,4.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.000000,NaN,106.0,NaN,NaN,92.0,0.033333,NaN,NaN,NaN,NaN,NaN,NaN
135774,2743086,Female,79,Caucasian,458,2014,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,9.000000,NaN,101.000000,NaN,1.070000,NaN,NaN,NaN,NaN,NaN,NaN,139.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130.000000,NaN,3.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.000000,0.70,NaN,5.90,NaN,NaN,0.190000,NaN,NaN,NaN,NaN,NaN,NaN
135775,2743099,Male,73,African American,458,2014,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,8.200000,NaN,103.400000,NaN,2.380000,0.2,0.333333,NaN,NaN,NaN,NaN,205.6,NaN,NaN,4.2,9.800000,NaN,9.666667,1.575,7.666667,NaN,7.26725,41.6,158.125,5.25,216.500000,NaN,3.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.800000,0.50,NaN,5.00,NaN,NaN,4.720000,NaN,NaN,NaN,NaN,NaN,NaN
135776,2743102,Male,81,Caucasian,459,2015,0,100 - 249,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,8.900000,NaN,109.000000,NaN,2.380000,0.1,2.000000,NaN,NaN,NaN,NaN,181.0,NaN,NaN,NaN,1.300000,53.0,10.000000,NaN,7.000000,NaN,NaN,NaN,NaN,NaN,268.000000,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.000000,0.40,NaN,5.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135777,2743110,Male,35,African American,458,2014,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,9.500000,NaN,101.000000,NaN,1.060000,NaN,1.000000,NaN,NaN,8.5,NaN,100.0,NaN,NaN,NaN,NaN,NaN,24.000000,2.200,10.000000,NaN,NaN,NaN,NaN,2.50,162.500000,NaN,4.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.000000,NaN,190.0,NaN,NaN,116.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# This distinction of numerical (continuous), binary, and categorical columns may be useful for you 
num_cols = feature_sets['labs'].tolist() + feature_sets['vitals'].tolist() + ['age', 'admissionheight', 'admissionweight']
bin_cols = feature_sets['icd10_before24h'].tolist() + feature_sets['admissiondx'].tolist()
cat_cols = ['hospital_region', 'ethnicity', 'gender', 'hospital_numbedscategory', 'hospitaldischargeyear', 'hospitalid']

# For privacy I think, the dataset sets the age of everyone over 89 as the string '>89'. We set back to a continuous number 
if 'age' in patient_agg.columns: 
    patient_agg.loc[patient_agg.age == '> 89', 'age'] = 90
    patient_agg['age'] = patient_agg['age'].astype(float)

In [24]:
Y_label = 'mortality_at48h'
X_covariate_names = num_cols + bin_cols + cat_cols

In [25]:
X = patient_agg[X_covariate_names].copy()
Y = patient_agg[Y_label].copy()
X

,24 h urine protein,24 h urine urea nitrogen,ALT (SGPT),ANF/ANA,AST (SGOT),Acetaminophen,Amikacin peak,Amikacin random,Amikacin trough,BNP,BUN,Base Deficit,Base Excess,CPK,CPKMB,CPKMB INDEX,CRP,CRPhs,Carbamazepine,Carboxyhemoglobin,Clostridium difficile toxin A+B,Cyclosporin,Device,Digoxin,ESR,Fe,Fe/TIBC Ratio,Ferritin,FiO2,Gentamicin peak,Gentamicin random,Gentamicin trough,HCO3,HDL,HIV 1&2 AB,HSV 1&2 IgG AB,HSV 1&2 IgG AB titer,Hct,Hgb,LDH,LDL,LPM O2,Legionella pneumophila Ab,Lidocaine,Lithium,MCH,MCHC,MCV,MPV,Methemoglobin,...,admissiondx_Splenectomy,admissiondx_Stereotactic procedure,admissiondx_Subarachnoid hemorrhage/arteriovenous malformation,admissiondx_Subarachnoid hemorrhage/intracranial aneurysm,"admissiondx_Subarachnoid hemorrhage/intracranial aneurysm, surgery for","admissiondx_TURP, transurethral prostate resection for benign prostatic hypertrophy","admissiondx_TURP, transurethral prostate resection for cancer","admissiondx_Tamponade, pericardial","admissiondx_Thoracotomy for benign tumor (i.e. mediastinal chest wall mass, thymectomy)",admissiondx_Thoracotomy for bronchopleural fistula,admissiondx_Thoracotomy for esophageal cancer,admissiondx_Thoracotomy for lung cancer,admissiondx_Thoracotomy for lung reduction,admissiondx_Thoracotomy for other malignancy in chest,admissiondx_Thoracotomy for other reasons,admissiondx_Thoracotomy for pleural disease,admissiondx_Thoracotomy for thoracic/respiratory infection,admissiondx_Thrombectomy (with general anesthesia),admissiondx_Thrombectomy (without general anesthesia),admissiondx_Thrombocytopenia,"admissiondx_Thrombosis, vascular (deep vein)","admissiondx_Thrombus, arterial",admissiondx_Thyroid neoplasm,admissiondx_Thyroidectomy,admissiondx_Thyroidectomy and Parathyroidectomy,"admissiondx_Toxicity, drug (i.e., beta blockers, calcium channel blockers, etc.)",admissiondx_Tracheostomy,admissiondx_Transphenoidal surgery,"admissiondx_Transplant, other","admissiondx_Trauma medical, other","admissiondx_Trauma surgery, other",admissiondx_Tricuspid valve surgery,"admissiondx_Tumor removal, intracardiac","admissiondx_Ulcer disease, peptic","admissiondx_Vascular medical, other","admissiondx_Vascular surgery, other",admissiondx_Vasculitis,admissiondx_Vena cava clipping,admissiondx_Vena cava filter insertion,admissiondx_Ventricular Septal Defect (VSD) Repair,admissiondx_Ventriculostomy,admissiondx_Weaning from mechanical ventilation (transfer from other unit or hospital only),admissiondx_Whipple-surgery for pancreatic cancer,admissiondx_nan,hospital_region,ethnicity,gender,hospital_numbedscategory,hospitaldischargeyear,hospitalid
0,NaN,NaN,199.0,NaN,468.5,NaN,NaN,NaN,NaN,NaN,26.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.250000,13.150,NaN,NaN,NaN,NaN,NaN,NaN,29.20,32.650000,89.350000,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Midwest,Caucasian,Female,<100,2015,59
1,NaN,NaN,52.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,15.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.600000,15.500,NaN,NaN,NaN,NaN,NaN,NaN,33.70,35.600000,94.800000,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,Midwest,Caucasian,Female,<100,2015,60
2,NaN,NaN,19.5,NaN,19.5,NaN,NaN,NaN,NaN,NaN,36.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.300000,9.350,NaN,NaN,NaN,NaN,NaN,NaN,26.40,33.050000,80.050000,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Midwest,Caucasian,Male,>= 500,2015,73
3,NaN,NaN,18.5,NaN,16.0,NaN,NaN,NaN,NaN,24.0,15.000000,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,34.050000,10.900,NaN,NaN,3.0,NaN,NaN,NaN,27.65,32.050000,86.250000,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,Midwest,Caucasian,Male,None,2015,67
4,NaN,NaN,18.0,NaN,31.5,NaN,NaN,NaN,NaN,NaN,9.333333,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.500,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,37.866667,11.800,NaN,NaN,NaN,NaN,NaN,NaN,28.10,31.133333,90.166667,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Midwest,Caucasian,Female,100 - 249,2014,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1608.0,16.000000,NaN,NaN,48.5,1.55,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,NaN,NaN,NaN,49.000000,16.300,NaN,66.0,NaN,NaN,NaN,NaN,30.00,33.000000,90.000000,10.80,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,South,Caucasian,Male,>= 500,2014,458
135774,NaN,NaN,12.0,NaN,18.0,NaN,NaN,NaN,NaN,734.0,32.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.000000,13.500,NaN,NaN,NaN,NaN,NaN,NaN,33.00,35.000000,94.000000,8.85,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,South,Caucasian,Female,>= 500,2014,458
135775,NaN,NaN,272.0,NaN,264.0,NaN,NaN,NaN,NaN,NaN,28.200000,NaN,-8.75,1375.5,146.50,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.375,NaN,NaN,NaN,18.5,NaN,NaN,NaN,NaN,31.750000,10.675,NaN,NaN,NaN,NaN,NaN,NaN,30.75,33.500000,91.500000,11.00,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,South,African American,Male,>= 500,2014,458
135776,NaN,NaN,21.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.000000,10.040,NaN,NaN,NaN,NaN,NaN,NaN,32.00,33.000000,97.000000,8.90,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,South,Caucasian,Male,100 - 249,2015,459
135777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN,133.0,1.10,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,44.500000,14.850,NaN,142.0,NaN,NaN,NaN,NaN,27.00,33.000000,82.000000,7.25,NaN,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,South,African American,Male,>= 500,2014,458

# Q1: Data preprocessing 
Right now dim(X) is huge with 1386 columns, highly sparse, and contains many missing features. 
We will need to do some preprocessing before we can train a model.

In [ ]:
na_drop_threshold = 0.95
bin_thresh = 0.01

mask = X.isna().mean() > na_drop_threshold
print(f"Dropping columns whose missing rate >{na_drop_threshold}: ", X.columns[mask])
X = X.drop(columns=X.columns[mask])
mask = ~X[bin_cols].mean().between(bin_thresh, 1 - bin_thresh)
print(f"Dropping binary columns whose mean before imputation are not in [{bin_thresh}, 1-{bin_thresh}]: ", X[bin_cols].columns[mask])
X = X.drop(columns=X[bin_cols].columns[mask])
mask = ~X[bin_cols].mean().between(bin_thresh, 1 - bin_thresh)
print(f"Dropping binary columns whose mean before imputation are not in [{bin_thresh}, 1-{bin_thresh}]: ", X[cat_cols].columns[mask])
X = X.drop(columns=X[cat_cols].columns[mask])

num_cols = np.intersect1d(X.columns, num_cols).tolist()
cat_cols = np.intersect1d(X.columns, cat_cols).tolist()
bin_cols = np.intersect1d(X.columns, bin_cols).tolist()

X

In [ ]:
# TODO: Choose your own way to preprocess X such that it no longer contains missing values and has reduced dimensionalitiy.
# You are free to use the above way but you can also do something else. 
# The goal is to get a dataset that is more manageable (for NxM matrix, a large M can lead to issues in modeling)
# This can be either by hand-selecting what features are relevant for Y, 
# removing features with low information (ie. high missingness rates, low variance, etc.)

# Q2: Train a naive logistic regression model to predict mortality

In [ ]:
### TODO: Use sklearn to build a simple logistic regression model to predict Y given X. 
# You can use your solution from week1 notebook. 
# Please use train_test_split to separate into training and test sets. 
## Output the AUROC and AUPRC score on the test set. 
## Hint: I recommend using StandardScaler for normalizing continuous features

# Introducing traditional fairness metrics 
In this section, we go through several common fairness metrics and if they make sense in a healthcare setting.

All of these metrics depend on:
- Y: the true outcome (e.g., mortality)
- $\hat{Y}$: the model prediction (0 or 1)
- A: a group attribute (e.g., race, gender)

We will compare these metrics across groups (e.g., If A is gender, we can compare across two gender categories observed in the data). 

------------------------------------------------------------
Demographic parity
------------------------------------------------------------

Definition: Satisfying demographic parity means

$$P(\hat{Y} = 1 | A = a) = P(\hat{Y} = 1 | A = b)$$



Empirical estimate of demographic parity in a dataset:

$$DP(a) = DP(b) \, \forall a,b \in A$$
where 
$$DP(a) = \frac{1 }{n_a} * \sum_{i : A_i = a} 1(\hat{Y}_i = 1)$$


Note: This is equivalent to the criteria $\hat{Y} \perp A$. 


In words:
A model with demographic parity would predict Y is "positive" (e.g., high risk) at the same rate across groups.


Interpretation:
This metric ignores the true outcome Y.
It only checks whether the model assigns positive predictions equally across groups.

Why this may be problematic in healthcare:
If groups have different true risk levels (e.g., due to structural inequities),
forcing equal prediction rates may lead to:
- under-treatment of higher-risk groups
- over-treatment of lower-risk groups

In [29]:
# If A = gender, these are all possible A=a values 
patient_agg.gender.value_counts(dropna=False)

gender
Male       72733
Female     62961
None          68
Unknown       10
Other          6
Name: count, dtype: int64

In [30]:
# If A = ethnicity, these are all possible A=a values 
patient_agg.ethnicity.value_counts(dropna=False)

ethnicity
Caucasian           104452
African American     15132
Other/Unknown         6296
Hispanic              5051
Asian                 2286
None                  1531
Native American       1030
Name: count, dtype: int64

# Q3: Estimate demographic parity
Note there are two parts, the calculation and the reflection.

In [ ]:
# TODO: Using the above equation, calculate the score DP(a) for all A, for both race and for sex.

In [ ]:
# TODO:  Reflection:
# Should a mortality prediction model flag high risk at the same rate across all groups,
# even if underlying risk differs?


------------------------------------------------------------
True positive rate parity (Equal Opportunity)
------------------------------------------------------------

Definition:

$$P(\hat{Y}= 1 | Y = 1, A = a) = P(\hat{Y}= 1 | Y = 1, A = b)$$



Empirical estimate in a dataset:

$$TPR(a) = TPR(b) \, \forall a,b \in A$$
where 
$$TPR(a) = \frac{1 }{n_a} * \sum_{i : A_i = a, Y_i=1} 1(\hat{Y}_i = 1)$$


Note: This is equivalent to the criteria $\hat{Y} \perp A \mid Y=1$. 



In words:
Among patients who truly experience the outcome (e.g., pass away in the hospital),
the model should identify them at equal rates across groups.

Interpretation:
This focuses on correctly identifying *true cases*.

Why this matters in healthcare:
Missing a high-risk patient (false negative) can be dangerous.
Equal opportunity ensures that one group is not systematically under-detected.

# Q4: Estimate true positive rate parity (equal opportunity)
Note there are two parts, the calculation and the reflection.

In [ ]:
# TODO: Using the above equation, calculate the score TPR(a) for all A, for both race and for sex.

In [ ]:
# TODO:  Reflection:
# For a mortality prediction model, is it more important to equalize:
# - overall prediction rates?
# - or the ability to detect true high-risk patients?


------------------------------------------------------------
False positive rate parity 
------------------------------------------------------------

Definition:

$$P(\hat{Y}= 1 | Y = 0, A = a) = P(\hat{Y}= 0 | Y = 0, A = b)$$



Empirical estimate in a dataset:

$$FPR(a) = FPR(b) \, \forall a,b \in A$$
where 
$$FPR(a) = \frac{1 }{n_a} * \sum_{i : A_i = a, Y_i=0} 1(\hat{Y}_i = 1)$$


Note: This is equivalent to the criteria $\hat{Y} \perp A \mid Y=0$. 




In words:
Among patients who do NOT experience the outcome,
how often does the model incorrectly predict high risk?

Interpretation:
This measures over-prediction.

Why this matters in healthcare:
False positives can lead to:
- unnecessary interventions
- alarm fatigue
- misallocation of limited resources


# Q5: Estimate false positive rate parity 
Note there are two parts, the calculation and the reflection.

In [ ]:
# TODO: Using the above equation, calculate the score FPR(a) for all A, for both race and for sex.

In [ ]:
# TODO:  Reflection:
# When (for our case of mortality, or for other cases of Y) might it be important to ensure that one group is not over-treated
# relative to another?

------------------------------------------------------------
Equalized odds
------------------------------------------------------------

Definition: Equalized odds would enforce 

$$P(\hat{Y}= 1 | Y = y, A = a) = P(\hat{Y} = 1 | Y = y, A = b)  \, \, y \in {0,1}$$

Empirical estimate in a dataset:

$$EO(a,y) = EO(b,y) \, \forall a,b \in A \, \, for y \in {0,1}$$
where 
$$EO(a,y) = \frac{1 }{n_{a,y}} * \sum_{i : A_i = a, Y_i=y} 1(\hat{Y}_i = 1)$$

Note: This is equivalent to the criteria $\hat{Y} \perp A \mid Y$. 

This means:
- equal TPR across groups
- equal FPR across groups

Interpretation:
The model should have similar error behavior across groups.

Why this is appealing:
It balances both:
- detecting true cases (TPR)
- avoiding false alarms (FPR)

Why this is difficult:
Equalized odds is stricter than just equal TPR or equal FPR. Because the constraints are stronger, enforcing it can conflict with:
- calibration
- overall accuracy

# Q6: Estimate equalized odds
Note there are two parts, the calculation and the reflection.

In [ ]:
# TODO: Using the above equation, calculate the score FPR(a) for all A, for both race and for sex.

In [ ]:
# TODO: Reflection:
# Would equalized odds be a good goal for mortality prediction?
# What tradeoffs might arise?

------------------------------------------------------------
Calibration
------------------------------------------------------------

Definition: 

$$P(Y = 1 | R = r, A = a) = r$$

where R is the predicted risk score (i.e. the continuous output in [0,1] of a logistic regression model, 
                                     prior to thresholding into 0 or 1). 


In words:
If the model predicts 0.2 risk, then about 20% of those patients
should actually experience the outcome — and this should hold across groups.

Interpretation:
Calibration is about whether predicted probabilities are meaningful.

Why this matters in healthcare:
Many clinical models output probabilities (risk scores),
which are used directly in decision-making.

Important note:
Calibration may conflict with equalized odds when base rates differ across groups.

# Q7: Tradeoffs

Enforcing fairness in a model often involves tradeoffs. In fact, there is a well-known [“impossibility theorem”](https://arxiv.org/abs/1609.07236) showing that certain fairness criteria (e.g., calibration and equalized odds) cannot all be satisfied at the same time when groups have different base rates. Similarly, there is often a tradeoff between training a “fair” model and training a highly accurate model. For example, enforcing certain fairness constraints may require the model to ignore predictive signals that differ across groups, which can reduce overall performance.

In [ ]:
# TODO:
# Did you observe in your evaluation that some metrics did better (showing the model was "more fair" for that metric) than other metrics?

# Q7: Who should we prioritize for fairness? 
So far, we (along with much of the algorithmic fairness literature) have evaluated fairness with respect to attributes such as gender and race/ethnicity, in part because these variables are what are available in the data.

In [ ]:
# TODO:
# Do you think that gender and race/ethnicity are the most important groups to consider in a healthcare setting?
# - Are there other patient characteristics or subgroups that should be prioritized when evaluating fairness?
# - What factors (e.g., clinical, social, or structural) might make a group particularly important to protect?

In [126]:
data_apache = data[['mortality_at48h', 'patienthealthsystemstayid']].merge(
    apache_ypred, on='patienthealthsystemstayid', how='inner')
y_ = data_apache.mortality_at48h
y_proba = data_apache.predictedicumortality
print(f"APACHE AUROC:", roc_auc_score(y_, y_proba))
print(f"APACHE AUPRC:", average_precision_score(y_, y_proba))

APACHE AUROC: 0.8613640402333097
APACHE AUPRC: 0.3256122955269497

In [81]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_validate, train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, LassoCV


preprocess = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="median", add_indicator=False), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse=True), cat_cols),
        ("bin", SimpleImputer(strategy="constant", fill_value=0, add_indicator=False), bin_cols),
    ]
)
data_pp = preprocess.fit_transform(data[num_cols + cat_cols + bin_cols])
data_pp = pd.DataFrame(data_pp, columns = preprocess.get_feature_names_out())
data_pp

,num__ALT (SGPT),num__AST (SGOT),num__BNP,num__BUN,num__Base Deficit,num__Base Excess,num__CPK,num__CPKMB,num__CPKMB INDEX,num__Carboxyhemoglobin,num__FiO2,num__HCO3,num__HDL,num__Hct,num__Hgb,num__LDL,num__LPM O2,num__MCH,num__MCHC,num__MCV,num__MPV,num__Methemoglobin,num__O2 Content,num__O2 Sat (%),num__PEEP,num__PT,num__PT INR,num__PTT,num__RBC,num__RDW,num__Respiratory Rate,num__TSH,num__TV,num__Temperature,num__Total CO2,num__Vent Rate,num__WBC x 1000,num__WBC's in urine,num__admissionheight,num__admissionweight,num__age,num__albumin,num__alkaline phos.,num__ammonia,num__anion gap,num__bands,num__basos,num__bedside glucose,num__bicarbonate,num__calcium,...,bin__K76.9,bin__K92.2,bin__N17.9,bin__N18.6,bin__N18.9,bin__N30.9,bin__N39.0,bin__R00.0,bin__R07.9,bin__R10.9,bin__R11.0,bin__R41.82,bin__R50.9,bin__R56.9,bin__R65.2,bin__R65.20,bin__R65.21,bin__R73.9,bin__S06.5,bin__S06.9,"bin__admissiondx_Angina, unstable (angina interferes w/quality of life or meds are tolerated poorly)",bin__admissiondx_Aortic valve replacement (isolated),"bin__admissiondx_Arrest, respiratory (without cardiac arrest)","bin__admissiondx_Bleeding, GI-location unknown","bin__admissiondx_Bleeding, lower GI","bin__admissiondx_Bleeding, upper GI","bin__admissiondx_CABG alone, coronary artery bypass grafting","bin__admissiondx_CHF, congestive heart failure","bin__admissiondx_CVA, cerebrovascular accident/stroke",bin__admissiondx_Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System),"bin__admissiondx_Coma/change in level of consciousness (for hepatic see GI, for diabetic see Endocrine, if related to cardiac arrest, see CV)",bin__admissiondx_Diabetic ketoacidosis,"bin__admissiondx_Embolus, pulmonary",bin__admissiondx_Emphysema/bronchitis,bin__admissiondx_Head only trauma,"bin__admissiondx_Hemorrhage/hematoma, intracranial","bin__admissiondx_Hypertension, uncontrolled (for cerebrovascular accident-see Neurological System)","bin__admissiondx_Infarction, acute myocardial (MI)","bin__admissiondx_Pneumonia, bacterial","bin__admissiondx_Renal failure, acute","bin__admissiondx_Respiratory - medical, other","bin__admissiondx_Rhythm disturbance (atrial, supraventricular)",bin__admissiondx_Rhythm disturbance (conduction defect),bin__admissiondx_Seizures (primary-no structural brain disease),"bin__admissiondx_Sepsis, GI","bin__admissiondx_Sepsis, cutaneous/soft tissue","bin__admissiondx_Sepsis, pulmonary","bin__admissiondx_Sepsis, renal/UTI (including bladder)","bin__admissiondx_Sepsis, unknown",bin__admissiondx_nan
0,199.0,468.5,505.525,26.500000,3.909091,-0.70,127.416667,4.20,2.9,1.05,40.000,23.026136,40.0,40.250000,13.150,83.0,4.0,29.20,32.650000,89.350000,9.80,0.45,15.9,97.000,5.000,21.233333,2.033333,29.000000,4.5050,17.950000,18.0,1.600,500.0000,37.0,25.0,16.0,12.250000,4.0,152.4,84.3,70.0,3.20,149.5,36.0,17.50,7.0,0.0,136.750000,24.000000,9.000000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,52.0,40.0,505.525,15.750000,3.909091,-0.70,127.416667,4.20,2.9,1.05,40.000,23.026136,40.0,43.600000,15.500,83.0,4.0,33.70,35.600000,94.800000,9.80,0.45,15.9,97.000,5.000,13.950000,1.140000,30.800000,4.6000,11.900000,18.0,1.600,500.0000,37.0,25.0,16.0,7.600000,4.0,162.6,54.4,52.0,4.00,81.0,36.0,17.25,7.0,0.0,136.750000,23.500000,8.100000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,19.5,19.5,505.525,36.000000,3.909091,-0.70,127.416667,4.20,2.9,1.05,40.000,23.026136,40.0,28.300000,9.350,83.0,4.0,26.40,33.050000,80.050000,9.80,0.45,15.9,97.000,5.000,12.100000,1.100000,24.000000,3.5350,15.850000,18.0,1.600,500.0000,37.0,20.0,16.0,12.950000,4.0,180.3,73.9,68.0,2.65,63.0,36.0,16.00,7.0,0.0,141.000000,19.500000,9.200000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,18.5,16.0,24.000,15.000000,3.909091,5.00,127.416667,4.20,2.9,1.05,40.000,30.000000,40.0,34.050000,10.900,83.0,3.0,27.65,32.050000,86.250000,9.80,0.45,15.9,97.000,5.000,13.950000,1.140000,30.800000,3.9500,13.650000,18.0,1.600,500.0000,37.0,25.0,16.0,27.850000,4.0,162.6,102.1,71.0,2.70,65.0,36.0,13.50,7.0,0.0,136.750000,29.500000,9.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,18.0,31.5,505.525,9.333333,3.909091,2.00,127.416667,4.20,2.9,1.05,60.500,25.000000,40.0,37.866667,11.800,83.0,4.0,28.10,31.133333,90.166667,9.80,0.45,15.9,97.000,5.000,58.950000,5.450000,49.000000,4.2000,15.633333,18.0,0.846,500.0000,37.0,35.0,16.0,10.466667,4.0,160.0,70.2,77.0,1.55,132.5,36.0,13.00,7.0,0.0,143.000000,29.666667,8.366667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135773,25.0,27.0,1608.000,16.000000,3.909091,-0.70,48.500000,1.55,3.2,1.05,40.000,23.026136,22.0,49.000000,16.300,66.0,4.0,30.00,33.000000,90.000000,10.80,0.45,15.9,97.000,5.000,13.950000,1.140000,30.800000,5.4900,14.100000,18.0,1.550,500.0000,37.0,25.0,16.0,5.400000,4.0,175.3,90.0,50.0,3.30,84.0,36.0,4.00,7.0,1.0,136.750000,24.000000,9.400000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135774,12.0,18.0,734.000,32.000000,3.909091,-0.70,127.416667,4.20,2.9,1.05,40.000,23.026136,40.0,39.000000,13.500,83.0,4.0,33.00,35.000000,94.000000,8.85,0.45,15.9,97.000,5.000,12.600000,1.270000,74.333333,4.1000,13.900000,18.0,1.600,500.0000,37.0,25.0,16.0,9.950000,4.0,162.6,78.4,79.0,3.50,93.0,36.0,12.00,7.0,0.1,136.750000,27.000000,9.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135775,272.0,264.0,505.525,28.200000,3.909091,-8.75,1375.500000,146.50,10.5,1.05,60.375,18.500000,40.0,31.750000,10.675,83.0,4.0,30.75,33.500000,91.500000,11.00,0.45,15.9,97.875,7.375,11.133333,1.100000,22.333333,3.4725,14.125000,18.0,1.600,412.6375,37.0,25.0,24.0,27.400000,4.0,177.8,102.0,73.0,3.30,62.0,36.0,15.20,7.0,0.0,216.315789,21.200000,8.200000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135776,21.0,15.0,505.525,42.000000,3.909091,-0.70,127.416667,4.20,2.9,1.05,40.000,23.026136,40.0,31.000000,10.040,83.0,4.0,32.00,33.000000,97.000000,8.90,0.45,15.9,97.000,5.000,10.900000,1.030000,26.000000,3.8900,15.000000,18.0,1.600,500.0000,37.0,25.0,16.0,13.500000,4.0,185.4,83.9,81.0,3.90,62.0,36.0,8.00,7.0,1.0,137.000000,24.000000,8.900000,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135777,25.0,27.0,505.525,13.000000,3.909091,-0.70,133.000000,1.10,0.8,1.05,40.000,23.026136,25.0,44.500000,14.850,142.0,4.0,27.00,33.000000,82.000000,7.25,0.45,15.9,97.000,5.000,13.950000,1.140000,40.666667,5.4550,13.400000,18.0,1.460,500.0000,37.0,25.0,16.0,6.450000,4.0,182.9,100.8,35.0,3.30,84.0,36.0,3.00,7.0,0.0,136.750000,31.000000,9.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
bin_cols_ = [x for x in data_pp.columns if 'bin_' in x]
mask = data_pp[bin_cols_].mean().between(bin_thresh, 1 - bin_thresh)
print(f"Dropping binary columns whose mean before imputation are not in [{bin_thresh}, 1-{bin_thresh}]: ", data_pp[bin_cols_].columns[mask])
# data_pp = data_pp.drop(columns=data_pp[bin_cols].columns[mask])

Dropping binary columns whose mean before imputation are not in [0.01, 1-0.01]:  Index(['bin__A41.9', 'bin__D69.6', 'bin__D72.829', 'bin__E03.9', 'bin__E10.1',
       'bin__E46', 'bin__E78.5', 'bin__E83.42', 'bin__E86.0', 'bin__E86.1',
       'bin__E87.0', 'bin__E87.1', 'bin__E87.2', 'bin__E87.5', 'bin__E87.6',
       'bin__F10.239', 'bin__F32.9', 'bin__G93.40', 'bin__I10', 'bin__I21.3',
       'bin__I21.4', 'bin__I25.10', 'bin__I26.99', 'bin__I46.9', 'bin__I48.0',
       'bin__I50.1', 'bin__I50.9', 'bin__I62.9', 'bin__I63.50', 'bin__I67.8',
       'bin__I95.9', 'bin__J18.9', 'bin__J44.1', 'bin__J44.9', 'bin__J45',
       'bin__J69.0', 'bin__J91.8', 'bin__J96.00', 'bin__J96.91', 'bin__K92.2',
       'bin__N17.9', 'bin__N18.6', 'bin__N18.9', 'bin__N30.9', 'bin__N39.0',
       'bin__R00.0', 'bin__R07.9', 'bin__R10.9', 'bin__R41.82', 'bin__R50.9',
       'bin__R56.9', 'bin__R65.2', 'bin__R65.20', 'bin__R65.21', 'bin__R73.9',
       'bin__S06.5', 'bin__S06.9',
       'bin__admissiondx_Angina, unstable (angina interferes w/quality of life or meds are tolerated poorly)',
       'bin__admissiondx_Aortic valve replacement (isolated)',
       'bin__admissiondx_Arrest, respiratory (without cardiac arrest)',
       'bin__admissiondx_Bleeding, GI-location unknown',
       'bin__admissiondx_Bleeding, lower GI',
       'bin__admissiondx_Bleeding, upper GI',
       'bin__admissiondx_CABG alone, coronary artery bypass grafting',
       'bin__admissiondx_CHF, congestive heart failure',
       'bin__admissiondx_CVA, cerebrovascular accident/stroke',
       'bin__admissiondx_Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System)',
       'bin__admissiondx_Coma/change in level of consciousness (for hepatic see GI, for diabetic see Endocrine, if related to cardiac arrest, see CV)',
       'bin__admissiondx_Diabetic ketoacidosis',
       'bin__admissiondx_Embolus, pulmonary',
       'bin__admissiondx_Emphysema/bronchitis',
       'bin__admissiondx_Head only trauma',
       'bin__admissiondx_Hemorrhage/hematoma, intracranial',
       'bin__admissiondx_Hypertension, uncontrolled (for cerebrovascular accident-see Neurological System)',
       'bin__admissiondx_Infarction, acute myocardial (MI)',
       'bin__admissiondx_Pneumonia, bacterial',
       'bin__admissiondx_Renal failure, acute',
       'bin__admissiondx_Respiratory - medical, other',
       'bin__admissiondx_Rhythm disturbance (atrial, supraventricular)',
       'bin__admissiondx_Rhythm disturbance (conduction defect)',
       'bin__admissiondx_Seizures (primary-no structural brain disease)',
       'bin__admissiondx_Sepsis, GI',
       'bin__admissiondx_Sepsis, cutaneous/soft tissue',
       'bin__admissiondx_Sepsis, pulmonary',
       'bin__admissiondx_Sepsis, renal/UTI (including bladder)',
       'bin__admissiondx_Sepsis, unknown', 'bin__admissiondx_nan'],
      dtype='object')

In [87]:
model.coef_.shape

(1, 445)

In [128]:

from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.preprocessing import StandardScaler

X = data_pp
y = data['mortality_at48h']
print(X.shape, y.shape)
model = LogisticRegressionCV(random_state=44, max_iter=100, n_jobs=-1, penalty='l1',
                             cv=3,
                             solver='saga')


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)
model.fit(X_train, y_train)

coef_df = pd.DataFrame({'feature': X.columns, 'coef': model.coef_.squeeze(), 
                        'abs_coef': np.abs(model.coef_).squeeze()}).sort_values('abs_coef')
from sklearn.metrics import roc_auc_score, average_precision_score
for X_, name, y_ in [[X_train, 'train', y_train], [X_test, 'test', y_test]]:
    y_proba = model.predict_proba(X_)[:, 1]
    print(f"{name.upper()} AUROC:", roc_auc_score(y_, y_proba))
    print(f"{name.upper()} AUPRC:", average_precision_score(y_, y_proba))

(135778, 445) (135778,)

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

TRAIN AUROC: 0.8654173337315287
TRAIN AUPRC: 0.31944541643316593
TEST AUROC: 0.859360393222773
TEST AUPRC: 0.30186139274328927

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [136]:

X = data_pp.drop(columns=[c for c in X.columns if 'gender' in c])
y = data['mortality_at48h']
print(X.shape, y.shape)
model = LogisticRegressionCV(random_state=44)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)
model.fit(X_train, y_train)

coef_df = pd.DataFrame({'feature': X.columns, 'coef': model.coef_.squeeze(), 
                        'abs_coef': np.abs(model.coef_).squeeze()}).sort_values('abs_coef')
from sklearn.metrics import roc_auc_score, average_precision_score
for X_, name, y_ in [[X_train, 'train', y_train], [X_test, 'test', y_test]]:
    y_proba = model.predict_proba(X_)[:, 1]
    print(f"{name.upper()} AUROC:", roc_auc_score(y_, y_proba))
    print(f"{name.upper()} AUPRC:", average_precision_score(y_, y_proba))
    
     
mask = ~data.gender.isin(['Female', 'Male'])
X = scaler.transform(X[mask])
y = y[mask]
y_proba = model.predict_proba(X)[:, 1]   
display(data[mask])
print(f"AUROC:", roc_auc_score(y, y_proba))
print(f"AUPRC:", average_precision_score(y, y_proba))

print("------"*10)


X = data_pp.drop(columns=[c for c in data_pp.columns if 'gender' in c])[data.gender.isin(['Female', 'Male'])]
Xheldout = data_pp.drop(columns=[c for c in data_pp.columns if 'gender' in c])[~data.gender.isin(['Female', 'Male'])]
y = data['mortality_at48h'][data.gender.isin(['Female', 'Male'])]
yheldout = data['mortality_at48h'][~data.gender.isin(['Female', 'Male'])]
print(X.shape, y.shape)
model = LogisticRegressionCV(random_state=44)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)
Xheldout= scaler.transform(Xheldout)
model.fit(X_train, y_train)

coef_df = pd.DataFrame({'feature': X.columns, 'coef': model.coef_.squeeze(), 
                        'abs_coef': np.abs(model.coef_).squeeze()}).sort_values('abs_coef')
from sklearn.metrics import roc_auc_score, average_precision_score
for X_, name, y_ in [[X_train, 'train', y_train], [X_test, 'test', y_test], [Xheldout, 'heldout', yheldout]]:
    y_proba = model.predict_proba(X_)[:, 1]
    print(f"{name.upper()} AUROC:", roc_auc_score(y_, y_proba))
    print(f"{name.upper()} AUPRC:", average_precision_score(y_, y_proba))

(135778, 440) (135778,)

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

TRAIN AUROC: 0.875091396266053
TRAIN AUPRC: 0.34138334502729983
TEST AUROC: 0.8637864148143812
TEST AUPRC: 0.3095319675260235

,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,hospitaldischargeyear,mortality_at48h,hospital_numbedscategory,hospital_region,"admissiondx_Angina, unstable (angina interferes w/quality of life or meds are tolerated poorly)",admissiondx_Aortic valve replacement (isolated),"admissiondx_Arrest, respiratory (without cardiac arrest)","admissiondx_Bleeding, GI-location unknown","admissiondx_Bleeding, lower GI","admissiondx_Bleeding, upper GI","admissiondx_CABG alone, coronary artery bypass grafting","admissiondx_CHF, congestive heart failure","admissiondx_CVA, cerebrovascular accident/stroke",admissiondx_Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System),"admissiondx_Coma/change in level of consciousness (for hepatic see GI, for diabetic see Endocrine, if related to cardiac arrest, see CV)",admissiondx_Diabetic ketoacidosis,"admissiondx_Embolus, pulmonary",admissiondx_Emphysema/bronchitis,admissiondx_Head only trauma,"admissiondx_Hemorrhage/hematoma, intracranial","admissiondx_Hypertension, uncontrolled (for cerebrovascular accident-see Neurological System)","admissiondx_Infarction, acute myocardial (MI)","admissiondx_Pneumonia, bacterial","admissiondx_Renal failure, acute","admissiondx_Respiratory - medical, other","admissiondx_Rhythm disturbance (atrial, supraventricular)",admissiondx_Rhythm disturbance (conduction defect),admissiondx_Seizures (primary-no structural brain disease),"admissiondx_Sepsis, GI","admissiondx_Sepsis, cutaneous/soft tissue","admissiondx_Sepsis, pulmonary","admissiondx_Sepsis, renal/UTI (including bladder)","admissiondx_Sepsis, unknown",admissiondx_nan,admissionheight,admissionweight,A41.9,D62,D69.6,D72.829,E03.9,E10.1,E46,E78.5,E83.42,...,PEEP,PT,PT INR,PTT,RBC,RDW,Respiratory Rate,TSH,TV,Temperature,Total CO2,Vent Rate,WBC x 1000,WBC's in urine,albumin,alkaline phos.,ammonia,anion gap,bands,basos,bedside glucose,bicarbonate,calcium,chloride,creatinine,direct bilirubin,eos,fibrinogen,glucose,ionized calcium,lactate,lipase,lymphs,magnesium,monos,pH,paCO2,paO2,phosphate,platelets x 1000,polys,potassium,sodium,total bilirubin,total cholesterol,total protein,triglycerides,troponin I,troponin T,urinary specific gravity
781,136001,None,NaN,None,67,2015,0,None,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1911,146319,None,NaN,None,60,2014,0,<100,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3461,159767,None,NaN,None,63,2014,0,100 - 249,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6843,190197,None,NaN,None,68,2015,0,<100,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7169,192868,None,NaN,None,68,2015,0,<100,Midwest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126807,2578450,Other,59.0,None,443,2015,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,167.0,58.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,10.3,0.90,25.4,3.895,14.35,NaN,NaN,NaN,NaN,NaN,NaN,3.40,NaN,4.3,90.0,NaN,15.000,NaN,NaN,84.000000,22.000,8.7500,102.50,0.90000,NaN,NaN,NaN,82.000,4.4088,1.6,NaN,NaN,1.80,NaN,7.425,33.5,261.5,2.60,131.0,NaN,3.50,139.0,0.23,NaN,7.2,NaN,NaN,NaN,1.006
127617,2587981,Other,90.0,Other/Unknown,443,2014,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,170.2,77.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,4.910,13.15,NaN,NaN,NaN,NaN,NaN,NaN,16.05,NaN,NaN,NaN,NaN,12.000,NaN,NaN,NaN,21.500,8.7500,109.50,0.61000,NaN,NaN,NaN,111.500,NaN,1.9,NaN,NaN,1.75,NaN,NaN,NaN,NaN,3.45,209.5,NaN,3.75,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128279,2596533,Other,41.0,African American,443,2015,0,>= 500,South,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,175.0,90.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,3.470,13.50,NaN,0.28,NaN,NaN,NaN,NaN,8.90,NaN,NaN,NaN,NaN,22.375,NaN,NaN,234.285714,11.375,7.5875,113.75,0.94375,NaN,NaN,NaN,282.375,NaN,1.3,NaN,NaN,1.80,NaN,NaN,NaN,NaN,NaN,192.0,NaN,3.95,147.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132541,2719220,None,NaN,None,458,2015,0,>= 500,South,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,149.9,36.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135204,2738996,Unknown,67.0,Caucasian,459,2015,0,100 - 249,South,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,NaN,99.8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,11.2,1.06,27.0,3.785,13.15,NaN,NaN,NaN,NaN,NaN,NaN,10.95,NaN,4.3,59.0,NaN,10.000,NaN,1.0,118.666667,24.500,7.0000,102.00,0.88000,NaN,0.5,NaN,131.000,NaN,2.2,NaN,8.0,NaN,5.5,NaN,NaN,NaN,NaN,93.0,NaN,3.90,137.0,0.70,NaN,6.6,NaN,NaN,NaN,1.015

IndexError: boolean index did not match indexed array along dimension 0; dimension is 27156 but corresponding boolean dimension is 135778

------------------------------------------------------------
(135694, 440) (135694,)

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

TRAIN AUROC: 0.8745169334905343
TRAIN AUPRC: 0.3333495562029647
TEST AUROC: 0.8680627648054795
TEST AUPRC: 0.3312141938411203
HELDOUT AUROC: 0.9958847736625515
HELDOUT AUPRC: 0.9166666666666665

In [135]:
coef_df[coef_df.coef==0].feature.tolist()

['cat__hospitalid_207',
 'cat__hospitalid_258',
 'cat__hospitalid_256',
 'cat__hospitalid_254',
 'cat__hospitalid_253',
 'bin__F32.9',
 'cat__hospitalid_251',
 'cat__hospitalid_250',
 'cat__hospitalid_249',
 'cat__hospitalid_262',
 'cat__hospitalid_248',
 'cat__hospitalid_245',
 'cat__hospitalid_244',
 'bin__F43.0',
 'cat__hospitalid_227',
 'cat__hospitalid_226',
 'cat__hospitalid_224',
 'cat__hospitalid_220',
 'cat__hospitalid_215',
 'cat__hospitalid_246',
 'cat__hospitalid_212',
 'cat__hospitalid_263',
 'cat__hospitalid_265',
 'cat__hospitalid_307',
 'cat__hospitalid_303',
 'cat__hospitalid_301',
 'cat__hospitalid_300',
 'cat__hospitalid_283',
 'cat__hospitalid_282',
 'cat__hospitalid_281',
 'cat__hospitalid_280',
 'cat__hospitalid_264',
 'cat__hospitalid_279',
 'cat__hospitalid_275',
 'bin__E87.6',
 'cat__hospitalid_272',
 'cat__hospitalid_271',
 'cat__hospitalid_269',
 'cat__hospitalid_268',
 'cat__hospitalid_267',
 'cat__hospitalid_266',
 'cat__hospitalid_277',
 'cat__hospitalid_210',
 'cat__hospitalid_209',
 'cat__hospitalid_208',
 'cat__hospitalid_167',
 'cat__hospitalid_165',
 'cat__hospitalid_164',
 'cat__hospitalid_158',
 'cat__hospitalid_157',
 'cat__hospitalid_156',
 'cat__hospitalid_155',
 'cat__hospitalid_154',
 'cat__hospitalid_171',
 'cat__hospitalid_152',
 'cat__hospitalid_148',
 'cat__hospitalid_146',
 'cat__hospitalid_144',
 'cat__hospitalid_143',
 'cat__hospitalid_142',
 'cat__hospitalid_141',
 'cat__hospitalid_140',
 'cat__hospitalid_136',
 'cat__hospitalid_151',
 'cat__hospitalid_174',
 'cat__hospitalid_175',
 'cat__hospitalid_176',
 'cat__hospitalid_205',
 'cat__hospitalid_204',
 'cat__hospitalid_203',
 'cat__hospitalid_202',
 'cat__hospitalid_201',
 'cat__hospitalid_200',
 'cat__hospitalid_199',
 'cat__hospitalid_198',
 'cat__hospitalid_197',
 'cat__hospitalid_196',
 'cat__hospitalid_195',
 'cat__hospitalid_194',
 'cat__hospitalid_188',
 'cat__hospitalid_184',
 'cat__hospitalid_183',
 'cat__hospitalid_182',
 'cat__hospitalid_181',
 'cat__hospitalid_180',
 'cat__hospitalid_179',
 'cat__hospitalid_310',
 'cat__hospitalid_135',
 'cat__hospitalid_312',
 'cat__hospitalid_323',
 'cat__hospitalid_433',
 'cat__hospitalid_429',
 'cat__hospitalid_428',
 'cat__hospitalid_425',
 'cat__hospitalid_424',
 'cat__hospitalid_423',
 'cat__hospitalid_422',
 'cat__hospitalid_421',
 'cat__hospitalid_434',
 'cat__hospitalid_420',
 'cat__hospitalid_417',
 'cat__hospitalid_416',
 'cat__hospitalid_414',
 'cat__hospitalid_413',
 'cat__hospitalid_412',
 'cat__hospitalid_411',
 'cat__hospitalid_409',
 'cat__hospitalid_408',
 'cat__hospitalid_419',
 'cat__hospitalid_407',
 'cat__hospitalid_435',
 'cat__hospitalid_437',
 'bin__E83.42',
 'bin__E78.5',
 'bin__E46',
 'bin__E87.0',
 'bin__E87.1',
 'bin__D72.829',
 'bin__D69.6',
 'bin__A41.9',
 'cat__hospitalid_436',
 'cat__hospitalid_459',
 'cat__hospitalid_452',
 'cat__hospitalid_449',
 'cat__hospitalid_447',
 'cat__hospitalid_445',
 'cat__hospitalid_444',
 'cat__hospitalid_440',
 'cat__hospitalid_439',
 'cat__hospitalid_438',
 'bin__E87.2',
 'cat__hospitalid_405',
 'cat__hospitalid_404',
 'cat__hospitalid_403',
 'cat__hospitalid_363',
 'cat__hospitalid_361',
 'cat__hospitalid_360',
 'cat__hospitalid_358',
 'cat__hospitalid_357',
 'cat__hospitalid_356',
 'cat__hospitalid_355',
 'cat__hospitalid_353',
 'cat__hospitalid_364',
 'cat__hospitalid_352',
 'cat__hospitalid_350',
 'cat__hospitalid_345',
 'cat__hospitalid_342',
 'cat__hospitalid_338',
 'cat__hospitalid_337',
 'cat__hospitalid_336',
 'cat__hospitalid_331',
 'cat__hospitalid_328',
 'cat__hospitalid_351',
 'cat__hospitalid_365',
 'cat__hospitalid_381',
 'cat__hospitalid_382',
 'cat__hospitalid_402',
 'cat__hospitalid_401',
 'cat__hospitalid_400',
 'cat__hospitalid_399',
 'cat__hospitalid_398',
 'cat__hospitalid_397',
 'cat__hospitalid_396',
 'cat__hospitalid_394',
 'cat__hospitalid_393',
 'cat__hospitalid_392',
 'cat__hospitalid_391',
 'cat__hospitalid_390',
 'cat__hospitalid_389',
 'cat__hospitalid_388',
 'cat__hospitalid_387',
 'cat__hospitalid_386',
 'cat__hospitalid_385',
 'cat__hospitalid_384',
 'cat__hospitalid_383',
 'cat__hospitalid_318',
 'cat__hospitalid_133',
 'cat__hospitalid_138',
 'cat__hospitalid_125',
 'num__noninvasivediastolic_bin1',
 'num__monos',
 'bin__R00.0',
 'bin__R07.9',
 'num__lipase',
 'bin__R11.0',
 'bin__R41.82',
 'bin__R50.9',
 'bin__R56.9',
 'num__heartrate_bin1',
 'num__glucose',
 'num__fibrinogen',
 'bin__R65.2',
 'num__direct bilirubin',
 'bin__R65.20',
 'num__cvp_bin1',
 'num__creatinine',
 'num__noninvasivediastolic_bin2',
 'bin__N30.9',
 'num__noninvasivemean_bin2',
 'bin__N18.9',
 'num__st1_bin2',
 'num__st1_bin1',
 'num__sodium',
 'bin__G47.33',
 'num__sao2_bin2',
 'bin__J18.9',
 'bin__J44.9',
 'bin__J45',
 'num__chloride',
 'num__potassium',
 'bin__J69.0',
 'bin__J91.8',
 'bin__J96.91',
 'bin__J96.92',
 'num__pH',
 'bin__K76.9',
 'bin__N17.9',
 'bin__N18.6',
 'num__polys',
 'bin__I67.8',
 'num__calcium',
 'bin__admissiondx_Angina, unstable (angina interferes w/quality of life or meds are tolerated poorly)',
 'num__MPV',
 'bin__admissiondx_Respiratory - medical, other',
 'num__MCHC',
 'num__MCH',
 'num__LDL',
 'num__Hgb',
 'num__Hct',
 'num__HDL',
 'num__HCO3',
 'num__Carboxyhemoglobin',
 'bin__admissiondx_Rhythm disturbance (conduction defect)',
 'num__CPK',
 'bin__admissiondx_Seizures (primary-no structural brain disease)',
 'num__Base Deficit',
 'bin__admissiondx_Sepsis, cutaneous/soft tissue',
 'num__BNP',
 'num__AST (SGOT)',
 'num__Methemoglobin',
 'num__O2 Content',
 'bin__admissiondx_Renal failure, acute',
 'num__PEEP',
 'num__basos',
 'bin__admissiondx_Bleeding, GI-location unknown',
 'bin__admissiondx_CHF, congestive heart failure',
 'num__admissionweight',
 'num__admissionheight',
 "num__WBC's in urine",
 'bin__admissiondx_Coma/change in level of consciousness (for hepatic see GI, for diabetic see Endocrine, if related to cardiac arrest, see CV)',
 'num__Vent Rate',
 'bin__R73.9',
 'num__Total CO2',
 'num__TV',
 'num__TSH',
 'num__Respiratory Rate',
 'bin__admissiondx_Embolus, pulmonary',
 'num__RBC',
 'bin__admissiondx_Emphysema/bronchitis',
 'bin__admissiondx_Hypertension, uncontrolled (for cerebrovascular accident-see Neurological System)',
 'bin__admissiondx_Infarction, acute myocardial (MI)',
 'num__Temperature',
 'num__st2_bin1',
 'bin__I95.9',
 'num__st2_bin3',
 'cat__hospitalid_69',
 'cat__hospitalid_68',
 'cat__hospitalid_67',
 'cat__hospitalid_63',
 'cat__hospitalid_61',
 'cat__hospitalid_60',
 'cat__hospitalid_59',
 'cat__hospitalid_58',
 'cat__hospitalid_56',
 'cat__hospitaldischargeyear_2015',
 'cat__hospitaldischargeyear_2014',
 'cat__hospital_region_None',
 'cat__hospital_region_West',
 'cat__hospital_region_South',
 'num__st2_bin2',
 'bin__I21.3',
 'cat__hospital_numbedscategory_None',
 'cat__hospitalid_71',
 'bin__G93.40',
 'cat__hospitalid_79',
 'cat__hospitalid_83',
 'cat__hospitalid_123',
 'cat__hospitalid_122',
 'cat__hospitalid_120',
 'cat__hospitalid_115',
 'cat__hospitalid_112',
 'cat__hospitalid_110',
 'cat__hospitalid_108',
 'cat__hospitalid_102',
 'bin__I21.4',
 'cat__hospitalid_96',
 'cat__hospitalid_94',
 'cat__hospitalid_93',
 'cat__hospitalid_92',
 'cat__hospitalid_91',
 'cat__hospitalid_90',
 'cat__hospitalid_86',
 'cat__hospitalid_85',
 'cat__hospitalid_84',
 'cat__hospitalid_95',
 'cat__hospital_numbedscategory_<100',
 'bin__I21.19',
 'bin__I50.1',
 'bin__I48.0',
 'num__triglycerides',
 'num__total cholesterol',
 'bin__I50.9',
 'num__temperature_bin3',
 'num__temperature_bin2',
 'num__temperature_bin1',
 'bin__I63.50',
 'bin__I26.99',
 'num__systemicsystolic_bin2',
 'num__systemicmean_bin3',
 'num__systemicmean_bin2',
 'num__systemicmean_bin1',
 'num__systemicdiastolic_bin3',
 'num__systemicdiastolic_bin1',
 'num__st3_bin3',
 'num__st3_bin2',
 'num__st3_bin1',
 'num__systemicsystolic_bin1',
 'num__urinary specific gravity',
 'bin__E86.1',
 'cat__ethnicity_African American',
 'cat__gender_Unknown',
 'cat__gender_Other',
 'cat__gender_Male',
 'cat__ethnicity_None',
 'cat__gender_None',
 'cat__ethnicity_Other/Unknown',
 'cat__gender_Female',
 'cat__hospital_numbedscategory_100 - 249',
 'bin__I25.10',
 'cat__ethnicity_Caucasian',
 'cat__hospital_numbedscategory_250 - 499',
 'cat__ethnicity_Asian',
 'cat__ethnicity_Native American']

In [131]:
coef_df[-50:]

                                               feature      coef  abs_coef
80                                      num__phosphate  0.024596  0.024596
5                                     num__Base Excess -0.025309  0.025309
108                         num__systemicsystolic_bin3 -0.025479  0.025479
257                                cat__hospitalid_273  0.026641  0.026641
396                                         bin__K92.2 -0.028695  0.028695
43                                        num__ammonia  0.029012  0.029012
26                                        num__PT  INR  0.031645  0.031645
134               cat__hospital_numbedscategory_>= 500  0.034861  0.034861
176                                cat__hospitalid_131  0.035093  0.035093
23                                     num__O2 Sat (%) -0.039024  0.039024
417  bin__admissiondx_Arrest, respiratory (without ...  0.039359  0.039359
65                                         num__lymphs -0.039830  0.039830
27                                            num__PTT  0.041096  0.041096
433              bin__admissiondx_Pneumonia, bacterial  0.041246  0.041246
241                                cat__hospitalid_252  0.042255  0.042255
112                               num__total bilirubin  0.042334  0.042334
81                               num__platelets x 1000 -0.044705  0.044705
56                                            num__eos -0.050810  0.050810
47                                num__bedside glucose  0.054014  0.054014
73                           num__noninvasivemean_bin3 -0.055439  0.055439
136                       cat__hospital_region_Midwest -0.056955  0.056955
36                                     num__WBC x 1000  0.057289  0.057289
349                                cat__hospitalid_458  0.059571  0.059571
137                     cat__hospital_region_Northeast  0.066500  0.066500
44                                      num__anion gap  0.068514  0.068514
114                                 num__total protein -0.073970  0.073970
79                                           num__paO2  0.075158  0.075158
89                                      num__sao2_bin3 -0.077002  0.077002
441                 bin__admissiondx_Sepsis, pulmonary  0.077441  0.077441
413                                         bin__S06.5  0.080979  0.080979
414                                         bin__S06.9  0.085349  0.085349
233                                cat__hospitalid_243 -0.085897  0.085897
426             bin__admissiondx_Diabetic ketoacidosis -0.088284  0.088284
85                               num__respiration_bin2  0.089436  0.089436
154                                 cat__hospitalid_73 -0.094385  0.094385
382                                         bin__I62.9  0.101555  0.101555
75                       num__noninvasivesystolic_bin2 -0.102124  0.102124
3                                             num__BUN  0.106185  0.106185
60                                 num__heartrate_bin2  0.114668  0.114668
430  bin__admissiondx_Hemorrhage/hematoma, intracra...  0.124288  0.124288
423  bin__admissiondx_CVA, cerebrovascular accident...  0.126636  0.126636
29                                            num__RDW  0.134004  0.134004
378                                         bin__I46.9  0.152412  0.152412
61                                 num__heartrate_bin3  0.160076  0.160076
392                                        bin__J96.00  0.192911  0.192911
424  bin__admissiondx_Cardiac arrest (with or witho...  0.201714  0.201714
444                               bin__admissiondx_nan -0.202236  0.202236
63                                        num__lactate  0.206807  0.206807
40                                            num__age  0.228719  0.228719
41                                        num__albumin -0.237710  0.237710

In [ ]:
model = LogisticRegressionCV(random_state=44)


X_train, X_test, y_train, y_test = train_test_split(
    X.to_numpy(), y, test_size=0.2, stratify=y, random_state=42
)
model.fit(X_train, y_train)

coef_df = pd.DataFrame({'feature': X.columns, 'coef': model.coef_, 'abs_coef': np.abs(model.coef_)}).sort_values('abs_coef')
from sklearn.metrics import roc_auc_score, average_precision_score
for X_, name, y_ in [[X_train, 'train', y_train], [X_test, 'test', y_test]]:
    y_proba = model.predict_proba(X_)[:, 1]
    print(f"{name.upper()} AUROC:", roc_auc_score(y_, y_proba))
    print(f"{name.upper()}  AUPRC:", average_precision_score(y_, y_proba))

In [91]:

from sklearn.linear_model import LogisticRegression, LogisticRegressionCV


X = data_pp.drop(columns=[c for c in data_pp.columns if 'hospitalid' in c])
y = data['mortality_at48h']
print(X.shape, y.shape)
model = LogisticRegressionCV(random_state=44, penalty='l1', solver='saga', max_iter=1000)


for id, counts in data.hospitalid.value_counts().items():
    if counts > 1000:
        print(f"id: {id}")
        mask = data.hospitalid==id 
        X_ = X[mask].to_numpy()
        y_ = y[mask]
        model.fit(X_, y[mask])
        y_proba = model.predict_proba(X_)[:, 1]
        print(f"{id} AUROC:", roc_auc_score(y_, y_proba))
        print(f"{id} AUPRC:", average_precision_score(y_, y_proba))
        # coef_df = pd.DataFrame({'feature': X.columns, 'coef': model.coef_, 'abs_coef': np.abs(model.coef_)}).sort_values('abs_coef')
        # from sklearn.metrics import roc_auc_score, average_precision_score
        for id2, counts2 in data.hospitalid.value_counts().items():
            if id2 != id and counts2 > 1000:
                X_ = X[data.hospitalid==id2]
                y_ = y[data.hospitalid==id2]
                y_proba = model.predict_proba(X_)[:, 1]
                print(f"--{id2} AUROC:", roc_auc_score(y_, y_proba))
                print(f"--{id2} AUPRC:", average_precision_score(y_, y_proba))

(135778, 237) (135778,)
id: 73

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

73 AUROC: 0.7492905242905243
73 AUPRC: 0.06069736663812419
--264 AUROC: 0.6549538953868036
--264 AUPRC: 0.06718386275164905
--420 AUROC: 0.6400001324222682
--420 AUPRC: 0.1571124271854858
--338 AUROC: 0.688504459164773
--338 AUPRC: 0.09697750758784682
--243 AUROC: 0.5932073299433944
--243 AUPRC: 0.03376402037024185
--458 AUROC: 0.5914739932606012
--458 AUPRC: 0.1564388195947931
--167 AUROC: 0.6509894654213262
--167 AUPRC: 0.11586667151812187
--300 AUROC: 0.6158037854444232
--300 AUPRC: 0.10547826445311492
--443 AUROC: 0.6591313235608538
--443 AUPRC: 0.12146705437718476
--188 AUROC: 0.6233207134878335
--188 AUPRC: 0.10390622897400481
--208 AUROC: 0.5177187909209952
--208 AUPRC: 0.07463489248449368
--252 AUROC: 0.6577388033069647
--252 AUPRC: 0.1417512748573732
--199 AUROC: 0.6864808751638671
--199 AUPRC: 0.1499358005861629
--122 AUROC: 0.5719243480722235
--122 AUPRC: 0.10509696215159262
--176 AUROC: 0.6440007829320807
--176 AUPRC: 0.09746879508851283
--281 AUROC: 0.6426723682821244
--281 AUPRC: 0.06081145504271271
--411 AUROC: 0.6742083091226031
--411 AUPRC: 0.08069291906444717
--413 AUROC: 0.6534024103468549
--413 AUPRC: 0.07657303171223076
--449 AUROC: 0.6520802741067058
--449 AUPRC: 0.10631448710265708
--283 AUROC: 0.5839170225747408
--283 AUPRC: 0.07281983108773514
--394 AUROC: 0.4853669711634833
--394 AUPRC: 0.06994486176286682
--307 AUROC: 0.7206871771371438
--307 AUPRC: 0.25755787821505355
--345 AUROC: 0.7294964028776977
--345 AUPRC: 0.12552491319685244
--148 AUROC: 0.650957329253262
--148 AUPRC: 0.12166966315833334
--165 AUROC: 0.6870513762504945
--165 AUPRC: 0.09584308937083252
--417 AUROC: 0.6427933459863796
--417 AUPRC: 0.09239232413098225
--416 AUROC: 0.7159020044543429
--416 AUPRC: 0.10812418719988899
--331 AUROC: 0.7249904543718977
--331 AUPRC: 0.10828158046694149
--248 AUROC: 0.628872356704488
--248 AUPRC: 0.12992400076210725
--183 AUROC: 0.6523090005232863
--183 AUPRC: 0.07872719136170381
--110 AUROC: 0.6518174620312388
--110 AUPRC: 0.1862756265603136
--365 AUROC: 0.598925
--365 AUPRC: 0.06122067546871542
--197 AUROC: 0.6801488361191275
--197 AUPRC: 0.137724231434166
--171 AUROC: 0.7931771293840258
--171 AUPRC: 0.16232986789522658
--277 AUROC: 0.690316004077472
--277 AUPRC: 0.13365947658738536
--440 AUROC: 0.5936832394639736
--440 AUPRC: 0.09310249609521358
--400 AUROC: 0.582440955448202
--400 AUPRC: 0.13333933245194374
--141 AUROC: 0.7367878206804381
--141 AUPRC: 0.1285659141463096
--142 AUROC: 0.6358108839121498
--142 AUPRC: 0.09993913689609003
--444 AUROC: 0.7098688750862664
--444 AUPRC: 0.16059367895808105
--79 AUROC: 0.6878207245898028
--79 AUPRC: 0.09183982393417633
--227 AUROC: 0.608926787498216
--227 AUPRC: 0.16022826193228273
--435 AUROC: 0.6958561020036431
--435 AUPRC: 0.10278100114380657
id: 264

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

264 AUROC: 0.5279311559146219
264 AUPRC: 0.05564369168612817
--73 AUROC: 0.5642496392496392
--73 AUPRC: 0.01571240047201466
--420 AUROC: 0.5624463689814079
--420 AUPRC: 0.130778322425189
--338 AUROC: 0.4684972626789764
--338 AUPRC: 0.03963649694370807
--243 AUROC: 0.3960891777799098
--243 AUPRC: 0.018340354050234643
--458 AUROC: 0.506630041111074
--458 AUPRC: 0.09053485537214476
--167 AUROC: 0.5802948771913858
--167 AUPRC: 0.11077791906630508
--300 AUROC: 0.5764730976868093
--300 AUPRC: 0.12631966314997467
--443 AUROC: 0.4810808132955784
--443 AUPRC: 0.06041949255341303
--188 AUROC: 0.5124626636480503
--188 AUPRC: 0.07046905030922897
--208 AUROC: 0.49737650953004514
--208 AUPRC: 0.041096617343884936
--252 AUROC: 0.47842938995618467
--252 AUPRC: 0.07864354113893628
--199 AUROC: 0.5300805290246753
--199 AUPRC: 0.09272919318353044
--122 AUROC: 0.5375030398711493
--122 AUPRC: 0.07867530851700813
--176 AUROC: 0.40861225288706204
--176 AUPRC: 0.03201838066932628
--281 AUROC: 0.4999736036321402
--281 AUPRC: 0.06690077325612458
--411 AUROC: 0.6341879721092389
--411 AUPRC: 0.08059064825579867
--413 AUROC: 0.5404835390946502
--413 AUPRC: 0.024046298756648
--449 AUROC: 0.5420949583945179
--449 AUPRC: 0.07617147927272121
--283 AUROC: 0.493300793166565
--283 AUPRC: 0.052032870499387665
--394 AUROC: 0.5159359697603161
--394 AUPRC: 0.08416107859449173
--307 AUROC: 0.5999156390601568
--307 AUPRC: 0.12090672126758498
--345 AUROC: 0.5294573037222396
--345 AUPRC: 0.06453579126754824
--148 AUROC: 0.4917973564537379
--148 AUPRC: 0.07331815395861384
--165 AUROC: 0.4967162154524388
--165 AUPRC: 0.05780139459802236
--417 AUROC: 0.5322652673886346
--417 AUPRC: 0.05146371110297056
--416 AUROC: 0.4405048255382331
--416 AUPRC: 0.03493404996898202
--331 AUROC: 0.5570828560519282
--331 AUPRC: 0.058932424410493664
--248 AUROC: 0.469533933484185
--248 AUPRC: 0.04997606020868887
--183 AUROC: 0.49846284667713253
--183 AUPRC: 0.04456592064724306
--110 AUROC: 0.5269560210177787
--110 AUPRC: 0.11258782150054673
--365 AUROC: 0.49267500000000003
--365 AUPRC: 0.03498491721067632
--197 AUROC: 0.4664093286260493
--197 AUPRC: 0.04826828243300742
--171 AUROC: 0.5358826996758032
--171 AUPRC: 0.035546712262504006
--277 AUROC: 0.5510295616717635
--277 AUPRC: 0.08492662826634267
--440 AUROC: 0.5060205865216547
--440 AUPRC: 0.048835641897921785
--400 AUROC: 0.5756172839506173
--400 AUPRC: 0.11888780935315699
--141 AUROC: 0.6162294081757169
--141 AUPRC: 0.13330071098646695
--142 AUROC: 0.57738829384399
--142 AUPRC: 0.08663456017140166
--444 AUROC: 0.5283988957902002
--444 AUPRC: 0.033285712978315174
--79 AUROC: 0.4935359541900672
--79 AUPRC: 0.045361315104631726
--227 AUROC: 0.4890823462252033
--227 AUPRC: 0.10492733121581274
--435 AUROC: 0.5018897996357012
--435 AUPRC: 0.05364805517780345
id: 420

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

420 AUROC: 0.5978534350336353
420 AUPRC: 0.1548147542350464
--73 AUROC: 0.6176887926887926
--73 AUPRC: 0.03860652970512281
--264 AUROC: 0.5604095224745032
--264 AUPRC: 0.058153963665033344
--338 AUROC: 0.5160773839566666
--338 AUPRC: 0.057335838311511275
--243 AUROC: 0.41042945888899546
--243 AUPRC: 0.023238197793762058
--458 AUROC: 0.5440331483520353
--458 AUPRC: 0.12940309415832946
--167 AUROC: 0.6010426502542633
--167 AUPRC: 0.11483028259176259
--300 AUROC: 0.5862206017303662
--300 AUPRC: 0.12123253582545562
--443 AUROC: 0.5053294952623811
--443 AUPRC: 0.0851746437462415
--188 AUROC: 0.5573614104511889
--188 AUPRC: 0.1408227540356272
--208 AUROC: 0.5084183580678017
--208 AUPRC: 0.05035407605560127
--252 AUROC: 0.5220476714447154
--252 AUPRC: 0.10255198231346815
--199 AUROC: 0.6041904798806594
--199 AUPRC: 0.12814838599257639
--122 AUROC: 0.5697974349467574
--122 AUPRC: 0.10285157557455843
--176 AUROC: 0.4515952241143081
--176 AUPRC: 0.0520683275001745
--281 AUROC: 0.5023228803716608
--281 AUPRC: 0.0465955124945488
--411 AUROC: 0.6950355897733876
--411 AUPRC: 0.09913097632152122
--413 AUROC: 0.5806731334509112
--413 AUPRC: 0.04571043020498346
--449 AUROC: 0.5749388154674498
--449 AUPRC: 0.09705515651288463
--283 AUROC: 0.4904942037827944
--283 AUPRC: 0.06426381472134479
--394 AUROC: 0.5198376335156496
--394 AUPRC: 0.07149648284707041
--307 AUROC: 0.6386695967338776
--307 AUPRC: 0.2536716294447259
--345 AUROC: 0.5620894588676886
--345 AUPRC: 0.1067485968472424
--148 AUROC: 0.5177228101491776
--148 AUPRC: 0.1286504804657886
--165 AUROC: 0.5117786695303227
--165 AUPRC: 0.06263613785168365
--417 AUROC: 0.5771114770570503
--417 AUPRC: 0.06249428487215511
--416 AUROC: 0.4680697847067558
--416 AUPRC: 0.04957534559055386
--331 AUROC: 0.6266841215294823
--331 AUPRC: 0.129388439387922
--248 AUROC: 0.5172963909554119
--248 AUPRC: 0.06961515391669787
--183 AUROC: 0.5439233385661957
--183 AUPRC: 0.07235756212033576
--110 AUROC: 0.5398258115597783
--110 AUPRC: 0.14630273428687895
--365 AUROC: 0.534825
--365 AUPRC: 0.03743319116055086
--197 AUROC: 0.49857170062845174
--197 AUPRC: 0.07368530710780627
--171 AUROC: 0.618884468022399
--171 AUPRC: 0.13776307735614401
--277 AUROC: 0.5809989806320082
--277 AUPRC: 0.1369364451435564
--440 AUROC: 0.5473392891823655
--440 AUPRC: 0.08765866048553801
--400 AUROC: 0.6181293612453032
--400 AUPRC: 0.14133560215335617
--141 AUROC: 0.7094918504314477
--141 AUPRC: 0.17875664571981545
--142 AUROC: 0.5766958779617007
--142 AUPRC: 0.09474566682453799
--444 AUROC: 0.6007936507936508
--444 AUPRC: 0.13275682791877788
--79 AUROC: 0.5837242594427927
--79 AUPRC: 0.06559110347381658
--227 AUROC: 0.5098829741686884
--227 AUPRC: 0.12099497038718132
--435 AUROC: 0.5651183970856102
--435 AUPRC: 0.08037908792396233
id: 338

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

338 AUROC: 0.6301791152186356
338 AUPRC: 0.08588512913238902
--73 AUROC: 0.6704204745871413
--73 AUPRC: 0.050702773254098187
--264 AUROC: 0.5610437386960787
--264 AUPRC: 0.05505114799672936
--420 AUROC: 0.6225157582499072
--420 AUPRC: 0.1550550273342333
--243 AUROC: 0.6204187853784899
--243 AUPRC: 0.043526900318358354
--458 AUROC: 0.5722381624943931
--458 AUPRC: 0.15255804307104764
--167 AUROC: 0.6756933937042809
--167 AUPRC: 0.12403554396733549
--300 AUROC: 0.5816936595187017
--300 AUPRC: 0.13666104790674555
--443 AUROC: 0.5607885775671011
--443 AUPRC: 0.09917475906278447
--188 AUROC: 0.5833630031064931
--188 AUPRC: 0.11515707819475277
--208 AUROC: 0.5325253710170231
--208 AUPRC: 0.07058249752585825
--252 AUROC: 0.4816102123356926
--252 AUPRC: 0.08674892301494773
--199 AUROC: 0.6016541707835275
--199 AUPRC: 0.1348588707606198
--122 AUROC: 0.6011250513289719
--122 AUPRC: 0.1199105944418638
--176 AUROC: 0.6077901742023879
--176 AUPRC: 0.07771905699369523
--281 AUROC: 0.5343240770070037
--281 AUPRC: 0.04420063901894388
--411 AUROC: 0.6884805345729228
--411 AUPRC: 0.0930493921695586
--413 AUROC: 0.5601410934744268
--413 AUPRC: 0.03835061121292875
--449 AUROC: 0.5889238514789176
--449 AUPRC: 0.10461649626048573
--283 AUROC: 0.5247651006711409
--283 AUPRC: 0.06208900518247557
--394 AUROC: 0.49674980670656627
--394 AUPRC: 0.07552797358644253
--307 AUROC: 0.6159181803032828
--307 AUPRC: 0.23494080513624324
--345 AUROC: 0.5619799812324053
--345 AUPRC: 0.10117322385773053
--148 AUROC: 0.6334948361596329
--148 AUPRC: 0.12526933287013994
--165 AUROC: 0.6580625105974114
--165 AUPRC: 0.09927742001325411
--417 AUROC: 0.5865454393212013
--417 AUPRC: 0.07978687747460922
--416 AUROC: 0.5314253897550111
--416 AUPRC: 0.056779673378193736
--331 AUROC: 0.6214340260732013
--331 AUPRC: 0.14487355368127797
--248 AUROC: 0.508342965049081
--248 AUPRC: 0.08085086438675515
--183 AUROC: 0.6771487441130298
--183 AUPRC: 0.08631655032026832
--110 AUROC: 0.6181674224429569
--110 AUPRC: 0.18944055804101506
--365 AUROC: 0.51535
--365 AUPRC: 0.03882080109488749
--197 AUROC: 0.5257679855851634
--197 AUPRC: 0.09199386967864864
--171 AUROC: 0.7131226053639846
--171 AUPRC: 0.10296096395624989
--277 AUROC: 0.6633639143730887
--277 AUPRC: 0.16868537665054284
--440 AUROC: 0.559016313847349
--440 AUPRC: 0.09732114827724375
--400 AUROC: 0.5921967257112184
--400 AUPRC: 0.1313483176127908
--141 AUROC: 0.7018071414044568
--141 AUPRC: 0.14899579945839625
--142 AUROC: 0.5748025532835659
--142 AUPRC: 0.09889181634263865
--444 AUROC: 0.6563319530710835
--444 AUPRC: 0.16420593886342
--79 AUROC: 0.5976434313401608
--79 AUPRC: 0.08118219664249685
--227 AUROC: 0.5823105465962608
--227 AUPRC: 0.16259631236401004
--435 AUROC: 0.5459471766848817
--435 AUPRC: 0.07866700537041466
id: 243

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

243 AUROC: 0.6245982442674853
243 AUPRC: 0.08267773201393164
--73 AUROC: 0.5587902837902838
--73 AUPRC: 0.020341858701718146
--264 AUROC: 0.5937913479915347
--264 AUPRC: 0.0573154476739546
--420 AUROC: 0.5869941469357487
--420 AUPRC: 0.135012268581335
--338 AUROC: 0.5694352207606541
--338 AUPRC: 0.05212572209453075
--458 AUROC: 0.5531376386896354
--458 AUPRC: 0.14015927732249567
--167 AUROC: 0.634925939409108
--167 AUPRC: 0.10162847898793934
--300 AUROC: 0.5713568857092874
--300 AUPRC: 0.06853315596050695
--443 AUROC: 0.5565346286822798
--443 AUPRC: 0.07067706517226857
--188 AUROC: 0.5252392380258685
--188 AUPRC: 0.07058181117764199
--208 AUROC: 0.4777662592754256
--208 AUPRC: 0.0505211949673357
--252 AUROC: 0.5071150300362814
--252 AUPRC: 0.09409647098096491
--199 AUROC: 0.5557503664813271
--199 AUPRC: 0.08249974004970066
--122 AUROC: 0.5684479314922677
--122 AUPRC: 0.09590893921281073
--176 AUROC: 0.6343237424153455
--176 AUPRC: 0.06359462638483696
--281 AUROC: 0.5362730088339844
--281 AUPRC: 0.039599676606697186
--411 AUROC: 0.6563105268254892
--411 AUPRC: 0.07147543122641714
--413 AUROC: 0.5727072310405644
--413 AUPRC: 0.07343257842403769
--449 AUROC: 0.5829382560660094
--449 AUPRC: 0.09706190835460846
--283 AUROC: 0.48998779743746185
--283 AUPRC: 0.04021949341353452
--394 AUROC: 0.41845164800549817
--394 AUPRC: 0.05247825671481852
--307 AUROC: 0.548851233127812
--307 AUPRC: 0.10462859777194418
--345 AUROC: 0.5566781357522678
--345 AUPRC: 0.0703921378388262
--148 AUROC: 0.5923859917548557
--148 AUPRC: 0.08754428992424328
--165 AUROC: 0.6126603741592721
--165 AUPRC: 0.09556006386684292
--417 AUROC: 0.5771184548397901
--417 AUPRC: 0.07348703700845835
--416 AUROC: 0.5403637713437268
--416 AUPRC: 0.06016293128111763
--331 AUROC: 0.4799269077619593
--331 AUPRC: 0.027062027044226698
--248 AUROC: 0.5285695681192922
--248 AUPRC: 0.06390243368890076
--183 AUROC: 0.5711178702250131
--183 AUPRC: 0.05243493685413524
--110 AUROC: 0.6228532354423091
--110 AUPRC: 0.11730848257177307
--365 AUROC: 0.552
--365 AUPRC: 0.05081017905135861
--197 AUROC: 0.5338470327996132
--197 AUPRC: 0.05059049182257018
--171 AUROC: 0.6079980842911877
--171 AUPRC: 0.04456761496467783
--277 AUROC: 0.5419469928644242
--277 AUPRC: 0.05208947026503033
--440 AUROC: 0.5306734317343174
--440 AUPRC: 0.060728844416062785
--400 AUROC: 0.5216384863123994
--400 AUPRC: 0.08468241542481778
--141 AUROC: 0.7170022371364653
--141 AUPRC: 0.1444103131695337
--142 AUROC: 0.5885967759385481
--142 AUPRC: 0.07435291249120389
--444 AUROC: 0.6335231193926845
--444 AUPRC: 0.09457948994626227
--79 AUROC: 0.6200969056271336
--79 AUPRC: 0.07415760616911188
--227 AUROC: 0.5895889824461253
--227 AUPRC: 0.10486715374311573
--435 AUROC: 0.6237249544626593
--435 AUPRC: 0.06990056161881669
id: 458

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

458 AUROC: 0.5940995043687467
458 AUPRC: 0.17316865506486867
--73 AUROC: 0.7320867404200738
--73 AUPRC: 0.05373295126326356
--264 AUROC: 0.6728034066471331
--264 AUPRC: 0.07243501401931456
--420 AUROC: 0.646349118067694
--420 AUPRC: 0.1672023420773417
--338 AUROC: 0.6879695525862672
--338 AUPRC: 0.09657433752056685
--243 AUROC: 0.6047113355080111
--243 AUPRC: 0.03819776486300397
--167 AUROC: 0.6692955711539119
--167 AUPRC: 0.11424626387936444
--300 AUROC: 0.63427064055465
--300 AUPRC: 0.09853222717671893
--443 AUROC: 0.6566882036680693
--443 AUPRC: 0.10832382543404154
--188 AUROC: 0.6396807623002727
--188 AUPRC: 0.1453373325728839
--208 AUROC: 0.5278308235122945
--208 AUPRC: 0.07305691385337934
--252 AUROC: 0.6491554154523286
--252 AUPRC: 0.13783206139366533
--199 AUROC: 0.6709029970746072
--199 AUPRC: 0.14781110232886047
--122 AUROC: 0.5922984615261946
--122 AUPRC: 0.11399424670654934
--176 AUROC: 0.6425875905265218
--176 AUPRC: 0.09680209176113806
--281 AUROC: 0.6420168584802731
--281 AUPRC: 0.05910083056930692
--411 AUROC: 0.7020990703079604
--411 AUPRC: 0.08880372235533544
--413 AUROC: 0.6642563198118753
--413 AUPRC: 0.07457872673282513
--449 AUROC: 0.6502167680581777
--449 AUPRC: 0.1078030697242604
--283 AUROC: 0.5699755948749237
--283 AUPRC: 0.06006031117727029
--394 AUROC: 0.49332779702757656
--394 AUPRC: 0.062178193131295814
--307 AUROC: 0.7205257457090485
--307 AUPRC: 0.2517866069049981
--345 AUROC: 0.7183140444166405
--345 AUPRC: 0.11892903694474094
--148 AUROC: 0.6441625228441499
--148 AUPRC: 0.15765402389899486
--165 AUROC: 0.6679082122873452
--165 AUPRC: 0.09073219424887084
--417 AUROC: 0.6450053031148821
--417 AUPRC: 0.08893708555416707
--416 AUROC: 0.6403414996288048
--416 AUPRC: 0.07687151515222725
--331 AUROC: 0.664743904434626
--331 AUPRC: 0.12870062571955226
--248 AUROC: 0.6432955118917775
--248 AUPRC: 0.11248085523682189
--183 AUROC: 0.6626193746729461
--183 AUPRC: 0.09401945619450719
--110 AUROC: 0.6401713092924495
--110 AUPRC: 0.17307948778447405
--365 AUROC: 0.6709375
--365 AUPRC: 0.06214262937830521
--197 AUROC: 0.6616834888592649
--197 AUPRC: 0.11018840513083877
--171 AUROC: 0.7840590922487474
--171 AUPRC: 0.1612587505701194
--277 AUROC: 0.6857186544342508
--277 AUPRC: 0.13149557686785288
--440 AUROC: 0.6097179063895903
--440 AUPRC: 0.12000740912500388
--400 AUROC: 0.5868827160493829
--400 AUPRC: 0.11980305532930587
--141 AUROC: 0.7566024579447398
--141 AUPRC: 0.21045911896523264
--142 AUROC: 0.6382884344909661
--142 AUPRC: 0.1060682446113497
--444 AUROC: 0.725
--444 AUPRC: 0.15016718264454484
--79 AUROC: 0.6919282017398964
--79 AUPRC: 0.09882313044405061
--227 AUROC: 0.6000428143285286
--227 AUPRC: 0.14657149621703858
--435 AUROC: 0.7115437158469946
--435 AUPRC: 0.1139548024633197
id: 167

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

167 AUROC: 0.6929798864631801
167 AUPRC: 0.1319334922565274
--73 AUROC: 0.6613215488215487
--73 AUPRC: 0.04586039027963441
--264 AUROC: 0.5434805649481858
--264 AUPRC: 0.05269500535664945
--420 AUROC: 0.6094754753959426
--420 AUPRC: 0.15642061070186247
--338 AUROC: 0.6020596921932618
--338 AUPRC: 0.07284858746329231
--243 AUROC: 0.6016202149093351
--243 AUPRC: 0.05153196782439366
--458 AUROC: 0.5715569938870909
--458 AUPRC: 0.1431012859015285
--300 AUROC: 0.5892129872601104
--300 AUPRC: 0.12135500711524028
--443 AUROC: 0.549379963809494
--443 AUPRC: 0.0846734689302721
--188 AUROC: 0.5738301729362747
--188 AUPRC: 0.11106198477292473
--208 AUROC: 0.5397797541102867
--208 AUPRC: 0.06686970898613229
--252 AUROC: 0.4903621205812962
--252 AUPRC: 0.08835373892450754
--199 AUROC: 0.5624325964959864
--199 AUPRC: 0.1156301270314852
--122 AUROC: 0.5963031180107881
--122 AUPRC: 0.11795587380978988
--176 AUROC: 0.6002309649637895
--176 AUPRC: 0.0661582822073901
--281 AUROC: 0.5306153873227044
--281 AUPRC: 0.043818140018439436
--411 AUROC: 0.6695901123377881
--411 AUPRC: 0.0867404876157316
--413 AUROC: 0.5628821281599059
--413 AUPRC: 0.038315285428036194
--449 AUROC: 0.5870183903223551
--449 AUPRC: 0.11069426464093003
--283 AUROC: 0.5106650396583282
--283 AUPRC: 0.06064988049062908
--394 AUROC: 0.522636808796999
--394 AUPRC: 0.07980008882701771
--307 AUROC: 0.6202195467422096
--307 AUPRC: 0.2274755067778568
--345 AUROC: 0.5335157960588052
--345 AUPRC: 0.09210169839246798
--148 AUROC: 0.6329370138977433
--148 AUPRC: 0.11662774170036974
--165 AUROC: 0.637478098683095
--165 AUPRC: 0.09796932110616673
--417 AUROC: 0.5657237356257675
--417 AUPRC: 0.06655318086169176
--416 AUROC: 0.5241425389755011
--416 AUPRC: 0.054093287449708524
--331 AUROC: 0.6103065510282005
--331 AUPRC: 0.11046997088898595
--248 AUROC: 0.4761269107424832
--248 AUPRC: 0.06097763383221721
--183 AUROC: 0.6131442961800104
--183 AUPRC: 0.07231592885895181
--110 AUROC: 0.624249622111855
--110 AUPRC: 0.18153324423953293
--365 AUROC: 0.5189375
--365 AUPRC: 0.03624633808321807
--197 AUROC: 0.4975609041501252
--197 AUPRC: 0.08406125229531788
--171 AUROC: 0.6899130562923667
--171 AUPRC: 0.07729563261100193
--277 AUROC: 0.6426095820591233
--277 AUPRC: 0.14404920132701138
--440 AUROC: 0.5238395805010682
--440 AUPRC: 0.08567206588617787
--400 AUROC: 0.5966787439613527
--400 AUPRC: 0.12486212665187475
--141 AUROC: 0.6816148057758796
--141 AUPRC: 0.15740331655396095
--142 AUROC: 0.5791950665368386
--142 AUPRC: 0.09129269729435521
--444 AUROC: 0.6433057280883367
--444 AUPRC: 0.15498998684315515
--79 AUROC: 0.5778218257901112
--79 AUPRC: 0.07380065970310684
--227 AUROC: 0.5580728795014509
--227 AUPRC: 0.14140157608838938
--435 AUROC: 0.48672586520947175
--435 AUPRC: 0.06763149857970976
id: 300

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

300 AUROC: 0.5189763279286246
300 AUPRC: 0.057748319825900014
--73 AUROC: 0.518414301747635
--73 AUPRC: 0.013549962065911652
--264 AUROC: 0.510854328568449
--264 AUPRC: 0.03901038451540917
--420 AUROC: 0.578856136447905
--420 AUPRC: 0.12655295441031378
--338 AUROC: 0.5700437826468095
--338 AUPRC: 0.05224697806401954
--243 AUROC: 0.5854900220665835
--243 AUPRC: 0.039556448723427694
--458 AUROC: 0.5497141872129362
--458 AUPRC: 0.1310015759521181
--167 AUROC: 0.6231214661949239
--167 AUPRC: 0.09668488622667258
--443 AUROC: 0.5398864744502329
--443 AUPRC: 0.06728767535976396
--188 AUROC: 0.5129545930167773
--188 AUPRC: 0.06671822033373202
--208 AUROC: 0.4958601593190747
--208 AUPRC: 0.07154619007457762
--252 AUROC: 0.5015885525089712
--252 AUPRC: 0.06901383815865914
--199 AUROC: 0.5005246979354347
--199 AUPRC: 0.06129138867273838
--122 AUROC: 0.520828599107773
--122 AUPRC: 0.08519312511434601
--176 AUROC: 0.6272969269915836
--176 AUPRC: 0.06980540054463831
--281 AUROC: 0.4928201879421392
--281 AUPRC: 0.036301192421126005
--411 AUROC: 0.49941894247530505
--411 AUPRC: 0.027133973996608253
--413 AUROC: 0.5002939447383892
--413 AUPRC: 0.02304147465437788
--449 AUROC: 0.5346898818264457
--449 AUPRC: 0.06358973522636122
--283 AUROC: 0.5097559487492374
--283 AUPRC: 0.03833768648900992
--394 AUROC: 0.4836058532115346
--394 AUPRC: 0.0626402101240952
--307 AUROC: 0.5
--307 AUPRC: 0.04594594594594595
--345 AUROC: 0.500735064122615
--345 AUPRC: 0.04567629588887755
--148 AUROC: 0.6067246801819031
--148 AUPRC: 0.08890058698200376
--165 AUROC: 0.6108347934211271
--165 AUPRC: 0.07640646773915612
--417 AUROC: 0.5567572848051802
--417 AUPRC: 0.07021766047019004
--416 AUROC: 0.5463845582776541
--416 AUPRC: 0.09708902706212073
--331 AUROC: 0.5
--331 AUPRC: 0.019579405366207395
--248 AUROC: 0.5
--248 AUPRC: 0.03471196454948301
--183 AUROC: 0.5384124803767661
--183 AUPRC: 0.05068202339568343
--110 AUROC: 0.6025840351256029
--110 AUPRC: 0.17722261581033832
--365 AUROC: 0.5600875
--365 AUPRC: 0.05769376633787013
--197 AUROC: 0.5650645298331454
--197 AUPRC: 0.061728416106579656
--171 AUROC: 0.5708259652225169
--171 AUPRC: 0.039850425343333835
--277 AUROC: 0.4913047910295616
--277 AUPRC: 0.04704051800326964
--440 AUROC: 0.519299864051272
--440 AUPRC: 0.06242780276049918
--400 AUROC: 0.4672638217928073
--400 AUPRC: 0.07348424090505604
--141 AUROC: 0.6575292716232314
--141 AUPRC: 0.09370001884347325
--142 AUROC: 0.5830790868765553
--142 AUPRC: 0.07964726390254001
--444 AUROC: 0.530624568668047
--444 AUPRC: 0.03022742093420176
--79 AUROC: 0.5408325074331022
--79 AUPRC: 0.0552438859542822
--227 AUROC: 0.5559321630750201
--227 AUPRC: 0.1274085574346945
--435 AUROC: 0.5442509107468124
--435 AUPRC: 0.0614740577628609
id: 443

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

443 AUROC: 0.6547222352591481
443 AUPRC: 0.11415148562557231
--73 AUROC: 0.7282888407888408
--73 AUPRC: 0.05946506086890952
--264 AUROC: 0.6519888063401108
--264 AUPRC: 0.06671655066289141
--420 AUROC: 0.6558947772657451
--420 AUPRC: 0.16651953125917068
--338 AUROC: 0.7016163113904914
--338 AUPRC: 0.09522527078857063
--243 AUROC: 0.6466918113786817
--243 AUPRC: 0.05106499534251224
--458 AUROC: 0.597410817884244
--458 AUPRC: 0.1717702591022728
--167 AUROC: 0.6832117950876554
--167 AUPRC: 0.12142939147713308
--300 AUROC: 0.6047825993548724
--300 AUPRC: 0.09879241713812073
--188 AUROC: 0.6217253403417413
--188 AUPRC: 0.13848245969137157
--208 AUROC: 0.5260916812163539
--208 AUPRC: 0.06848693230756825
--252 AUROC: 0.6532061004381531
--252 AUPRC: 0.1414360539214144
--199 AUROC: 0.6866374773169046
--199 AUPRC: 0.16390674889915577
--122 AUROC: 0.5955875024418638
--122 AUPRC: 0.12187592408816617
--176 AUROC: 0.6615854374633001
--176 AUPRC: 0.08313008406946389
--281 AUROC: 0.6277672192306338
--281 AUPRC: 0.06023185781643964
--411 AUROC: 0.6656619213635484
--411 AUPRC: 0.08567324155067593
--413 AUROC: 0.6499559082892415
--413 AUPRC: 0.07943733638651096
--449 AUROC: 0.6638661632053704
--449 AUPRC: 0.10842603886603189
--283 AUROC: 0.5542647956070774
--283 AUPRC: 0.07155520789497904
--394 AUROC: 0.5015033933736147
--394 AUPRC: 0.07162783077465355
--307 AUROC: 0.7206194800866522
--307 AUPRC: 0.25771730819665073
--345 AUROC: 0.7250469189865498
--345 AUPRC: 0.12472668747659185
--148 AUROC: 0.6635694249649369
--148 AUPRC: 0.14542320747744
--165 AUROC: 0.69078166506528
--165 AUPRC: 0.1061271371707718
--417 AUROC: 0.6325778720553757
--417 AUPRC: 0.09396451270513137
--416 AUROC: 0.7312472160356347
--416 AUPRC: 0.1270804421931361
--331 AUROC: 0.7325178639611629
--331 AUPRC: 0.14085892105532852
--248 AUROC: 0.6204235784401503
--248 AUPRC: 0.12892625859024673
--183 AUROC: 0.6707384877027733
--183 AUPRC: 0.09302690405889008
--110 AUROC: 0.6762614266177212
--110 AUPRC: 0.2078174427128815
--365 AUROC: 0.6758125
--365 AUPRC: 0.06499245339246298
--197 AUROC: 0.6941534945724623
--197 AUPRC: 0.14130159266805475
--171 AUROC: 0.8056108163866784
--171 AUPRC: 0.10748575547246075
--277 AUROC: 0.6746992864424058
--277 AUPRC: 0.153510358556447
--440 AUROC: 0.6164546513886192
--440 AUPRC: 0.1197554122084848
--400 AUROC: 0.582776435856146
--400 AUPRC: 0.12896925745153226
--141 AUROC: 0.7299601964031495
--141 AUPRC: 0.18548561655193502
--142 AUROC: 0.6264308125067619
--142 AUPRC: 0.1140235162167684
--444 AUROC: 0.6986024844720496
--444 AUPRC: 0.1601065045330804
--79 AUROC: 0.6768527695187754
--79 AUPRC: 0.09321650591223113
--227 AUROC: 0.6299295942153085
--227 AUPRC: 0.18190235310958328
--435 AUROC: 0.6967213114754098
--435 AUPRC: 0.11599866606572065
id: 188

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

188 AUROC: 0.6295255463541511
188 AUPRC: 0.16947551449544587
--73 AUROC: 0.7125440917107584
--73 AUPRC: 0.06126615016724081
--264 AUROC: 0.5975564725953632
--264 AUPRC: 0.06714394168490911
--420 AUROC: 0.6406158959690662
--420 AUPRC: 0.17548001385341533
--338 AUROC: 0.5845913096396687
--338 AUPRC: 0.08877246481978919
--243 AUROC: 0.45973448143528733
--243 AUPRC: 0.026267898923818443
--458 AUROC: 0.5969631927994454
--458 AUPRC: 0.17620198102384937
--167 AUROC: 0.6100129691357322
--167 AUPRC: 0.11223442368329249
--300 AUROC: 0.6101750315351399
--300 AUPRC: 0.11002666137430075
--443 AUROC: 0.569246935018747
--443 AUPRC: 0.10703626888743392
--208 AUROC: 0.5120171322566565
--208 AUPRC: 0.06904943597137511
--252 AUROC: 0.6128838795376593
--252 AUPRC: 0.1306884524342865
--199 AUROC: 0.6647648384576141
--199 AUPRC: 0.1633167687406992
--122 AUROC: 0.5984639182244761
--122 AUPRC: 0.13296890082698587
--176 AUROC: 0.5775846545312194
--176 AUPRC: 0.10410860549621373
--281 AUROC: 0.5850183014817161
--281 AUPRC: 0.05561369465111439
--411 AUROC: 0.7047077764865388
--411 AUPRC: 0.09339737239865875
--413 AUROC: 0.6219944150499708
--413 AUPRC: 0.07112547352235524
--449 AUROC: 0.641801272638277
--449 AUPRC: 0.11121264875549812
--283 AUROC: 0.5585234899328859
--283 AUPRC: 0.06893232149702039
--394 AUROC: 0.5416797915294522
--394 AUPRC: 0.07157325819982563
--307 AUROC: 0.6912181303116147
--307 AUPRC: 0.2639362773436261
--345 AUROC: 0.6463403190491086
--345 AUPRC: 0.11277413802574947
--148 AUROC: 0.5839124059671044
--148 AUPRC: 0.15656129888999595
--165 AUROC: 0.5865313965975244
--165 AUPRC: 0.08229355604020638
--417 AUROC: 0.623792843586022
--417 AUPRC: 0.08787718903008723
--416 AUROC: 0.5548255382331106
--416 AUPRC: 0.08075467034557271
--331 AUROC: 0.7144220804014618
--331 AUPRC: 0.13693857583314073
--248 AUROC: 0.584194761431897
--248 AUPRC: 0.11391067873288485
--183 AUROC: 0.6432823129251701
--183 AUPRC: 0.11234392730419697
--110 AUROC: 0.6069171525228533
--110 AUPRC: 0.17020038751976313
--365 AUROC: 0.5846874999999999
--365 AUPRC: 0.059925539339494044
--197 AUROC: 0.5710414133571627
--197 AUPRC: 0.11909169634797523
--171 AUROC: 0.6462938402593575
--171 AUPRC: 0.1773387587495438
--277 AUROC: 0.6557798165137615
--277 AUPRC: 0.18416856824998643
--440 AUROC: 0.6006020586521654
--440 AUPRC: 0.13326609918534793
--400 AUROC: 0.6066626409017714
--400 AUPRC: 0.1507068804436136
--141 AUROC: 0.7220866381940207
--141 AUPRC: 0.21016460298692602
--142 AUROC: 0.6070431678026614
--142 AUPRC: 0.09573629415429363
--444 AUROC: 0.6875086266390613
--444 AUPRC: 0.16745469918658648
--79 AUROC: 0.6628124655874904
--79 AUPRC: 0.09917116197723136
--227 AUROC: 0.5920508063365207
--227 AUPRC: 0.14614592230215978
--435 AUROC: 0.628950364298725
--435 AUPRC: 0.11818846934925556
id: 208

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

208 AUROC: 0.49173395896988215
208 AUPRC: 0.07538257105413275
--73 AUROC: 0.5493045534712201
--73 AUPRC: 0.018930112915015
--264 AUROC: 0.5160631070782633
--264 AUPRC: 0.04043056005743872
--420 AUROC: 0.589865061708777
--420 AUPRC: 0.13208275493482868
--338 AUROC: 0.570285275458776
--338 AUPRC: 0.05227400188327848
--243 AUROC: 0.5801772522306438
--243 AUPRC: 0.04034116653779475
--458 AUROC: 0.5426643238173615
--458 AUPRC: 0.12979193787369045
--167 AUROC: 0.6231897248040409
--167 AUPRC: 0.09694051785342733
--300 AUROC: 0.5469957983838049
--300 AUPRC: 0.0770304810359101
--443 AUROC: 0.5282679661874292
--443 AUPRC: 0.06808463017558539
--188 AUROC: 0.5115087011705745
--188 AUPRC: 0.0670888762016663
--252 AUROC: 0.45074867661928264
--252 AUPRC: 0.06627410835445996
--199 AUROC: 0.527652388425002
--199 AUPRC: 0.07413352034701345
--122 AUROC: 0.5278671466673046
--122 AUPRC: 0.08889847211226153
--176 AUROC: 0.6268898023096496
--176 AUPRC: 0.06798153417345701
--281 AUROC: 0.49543342836025756
--281 AUPRC: 0.03557328862269955
--411 AUROC: 0.5586868099941895
--411 AUPRC: 0.05513293501014996
--413 AUROC: 0.467092886537331
--413 AUPRC: 0.022348838291286546
--449 AUROC: 0.5515558352562759
--449 AUPRC: 0.08258576365698655
--283 AUROC: 0.5087187309334961
--283 AUPRC: 0.04020186814142047
--394 AUROC: 0.4861401448984851
--394 AUPRC: 0.06299065569651778
--307 AUROC: 0.4788316530578237
--307 AUPRC: 0.06704233238373562
--345 AUROC: 0.505270566155771
--345 AUPRC: 0.06044156879035155
--148 AUROC: 0.6060234179098134
--148 AUPRC: 0.08837786379894957
--165 AUROC: 0.6106765387441362
--165 AUPRC: 0.07655498664764773
--417 AUROC: 0.5563316400580551
--417 AUPRC: 0.07012375946462629
--416 AUROC: 0.5280697847067557
--416 AUPRC: 0.09135652392193747
--331 AUROC: 0.5004909180166912
--331 AUPRC: 0.04558770063147083
--248 AUROC: 0.47562226310049
--248 AUPRC: 0.06794411427668803
--183 AUROC: 0.5543890633176347
--183 AUPRC: 0.05177260641617293
--110 AUROC: 0.5935938962067229
--110 AUPRC: 0.17169707203354548
--365 AUROC: 0.572925
--365 AUPRC: 0.05975613482609323
--197 AUROC: 0.5603401549887933
--197 AUPRC: 0.05834667214864503
--171 AUROC: 0.5708259652225169
--171 AUPRC: 0.039850425343333835
--277 AUROC: 0.5338939857288482
--277 AUPRC: 0.06152402304073781
--440 AUROC: 0.5191663429792193
--440 AUPRC: 0.06267607285966896
--400 AUROC: 0.47485238862050455
--400 AUPRC: 0.09373081934290284
--141 AUROC: 0.6465179116185827
--141 AUPRC: 0.09400232063704647
--142 AUROC: 0.580450070323488
--142 AUPRC: 0.07955280348714905
--444 AUROC: 0.5596618357487922
--444 AUPRC: 0.03798236429208934
--79 AUROC: 0.5307234886025768
--79 AUPRC: 0.055182862164682676
--227 AUROC: 0.5648874934589221
--227 AUPRC: 0.12989339630706764
--435 AUROC: 0.5241347905282331
--435 AUPRC: 0.059905958500403644
id: 252

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

252 AUROC: 0.6314471440750212
252 AUPRC: 0.12726752571000138
--73 AUROC: 0.6113175404842072
--73 AUPRC: 0.015804090635748395
--264 AUROC: 0.641865279482507
--264 AUPRC: 0.06563990066221133
--420 AUROC: 0.5677624609354308
--420 AUPRC: 0.11436899354190563
--338 AUROC: 0.5492778157458142
--338 AUPRC: 0.05549446694664344
--243 AUROC: 0.4176850474911254
--243 AUPRC: 0.02664986565555319
--458 AUROC: 0.5146789517973582
--458 AUPRC: 0.09202079523221798
--167 AUROC: 0.5846947133707239
--167 AUPRC: 0.09865703820927299
--300 AUROC: 0.6060746960810491
--300 AUPRC: 0.08181640243481043
--443 AUROC: 0.5430244624875498
--443 AUPRC: 0.07334046476414165
--188 AUROC: 0.5937179804261032
--188 AUPRC: 0.10682227796207368
--208 AUROC: 0.4605089662447257
--208 AUPRC: 0.03622739429912634
--199 AUROC: 0.655023215865574
--199 AUPRC: 0.12909739029894052
--122 AUROC: 0.5292844242982383
--122 AUPRC: 0.07361887031406693
--176 AUROC: 0.41520454100606774
--176 AUPRC: 0.03137599684359732
--281 AUROC: 0.5561890683841904
--281 AUPRC: 0.039901217619463275
--411 AUROC: 0.688976854541933
--411 AUPRC: 0.08243033696993796
--413 AUROC: 0.6591563786008229
--413 AUPRC: 0.07256702180457111
--449 AUROC: 0.5919131529263688
--449 AUPRC: 0.08549864703134866
--283 AUROC: 0.5310189139719341
--283 AUPRC: 0.042325998620232924
--394 AUROC: 0.44354399931273436
--394 AUPRC: 0.060732270713367606
--307 AUROC: 0.7193384435927346
--307 AUPRC: 0.2320564894301706
--345 AUROC: 0.710361276196434
--345 AUPRC: 0.09827012951933102
--148 AUROC: 0.5100036125632199
--148 AUPRC: 0.0840950478717192
--165 AUROC: 0.5350364550952353
--165 AUPRC: 0.06100139078764422
--417 AUROC: 0.595902645975215
--417 AUPRC: 0.05203539781125948
--416 AUROC: 0.5090497401633258
--416 AUPRC: 0.04237042905085895
--331 AUROC: 0.643961708394698
--331 AUPRC: 0.07836933154353073
--248 AUROC: 0.6249654072180892
--248 AUPRC: 0.10774270014277777
--183 AUROC: 0.5244309262166404
--183 AUPRC: 0.046058719499350524
--110 AUROC: 0.5283452098178939
--110 AUPRC: 0.09732947766167457
--365 AUROC: 0.5945125
--365 AUPRC: 0.057065236742307644
--197 AUROC: 0.5195493898598068
--197 AUPRC: 0.05445004961888194
--171 AUROC: 0.5933355437665782
--171 AUPRC: 0.05134533331133958
--277 AUROC: 0.5704179408766565
--277 AUPRC: 0.09635372653634061
--440 AUROC: 0.5768110312682073
--440 AUPRC: 0.046626421635995334
--400 AUROC: 0.5747383252818035
--400 AUPRC: 0.11451583290070483
--141 AUROC: 0.7584037886051309
--141 AUPRC: 0.16696954722369772
--142 AUROC: 0.6412744779833388
--142 AUPRC: 0.09782629523242309
--444 AUROC: 0.6260006901311249
--444 AUPRC: 0.05619912962379546
--79 AUROC: 0.5807400066072018
--79 AUPRC: 0.05594249167496138
--227 AUROC: 0.5558370201227344
--227 AUPRC: 0.09539789082668895
--435 AUROC: 0.6264116575591986
--435 AUPRC: 0.08246539778871088
id: 199

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

199 AUROC: 0.7109931482521908
199 AUPRC: 0.2067614927990971
--73 AUROC: 0.6185425685425685
--73 AUPRC: 0.03716804775468025
--264 AUROC: 0.6645987684922748
--264 AUPRC: 0.07031328349555198
--420 AUROC: 0.6472734254992321
--420 AUPRC: 0.13832161886178598
--338 AUROC: 0.585352011997363
--338 AUPRC: 0.06735391874835135
--243 AUROC: 0.4761824810515206
--243 AUPRC: 0.024022871673053857
--458 AUROC: 0.5919253253854394
--458 AUPRC: 0.13505183467824128
--167 AUROC: 0.6550977804575602
--167 AUPRC: 0.11845716859350405
--300 AUROC: 0.6866558020053586
--300 AUPRC: 0.14194327237199067
--443 AUROC: 0.5604235436450201
--443 AUPRC: 0.10209443651863778
--188 AUROC: 0.6291341771326225
--188 AUPRC: 0.1834792622940951
--208 AUROC: 0.564873417721519
--208 AUPRC: 0.045495490546750644
--252 AUROC: 0.6855706893475287
--252 AUPRC: 0.15598153670923623
--122 AUROC: 0.5740911283603034
--122 AUPRC: 0.0826829382699829
--176 AUROC: 0.49835975729105497
--176 AUPRC: 0.06260924899976243
--281 AUROC: 0.6004469784957589
--281 AUPRC: 0.056960818153890445
--411 AUROC: 0.7316845826070114
--411 AUPRC: 0.10402431392536801
--413 AUROC: 0.738286302175191
--413 AUPRC: 0.08514577591695563
--449 AUROC: 0.6283896231032795
--449 AUPRC: 0.09010568446542538
--283 AUROC: 0.6533740085417937
--283 AUPRC: 0.08979290024133228
--394 AUROC: 0.6542911142292602
--394 AUPRC: 0.08560651161066442
--307 AUROC: 0.7213901849691718
--307 AUPRC: 0.26164527023059436
--345 AUROC: 0.6855489521426337
--345 AUPRC: 0.11088073374561334
--148 AUROC: 0.5972842024735433
--148 AUPRC: 0.16814057723774536
--165 AUROC: 0.5653196179279941
--165 AUPRC: 0.07822819202369644
--417 AUROC: 0.6545020654236909
--417 AUPRC: 0.07148415648967313
--416 AUROC: 0.6319079435783223
--416 AUPRC: 0.0844997346005238
--331 AUROC: 0.7766050291823487
--331 AUPRC: 0.15899624410579793
--248 AUROC: 0.7643946670139511
--248 AUPRC: 0.1596159897945039
--183 AUROC: 0.5912970957613815
--183 AUPRC: 0.1035830235209604
--110 AUROC: 0.5618512920175628
--110 AUPRC: 0.1197909167780284
--365 AUROC: 0.6450750000000001
--365 AUPRC: 0.05491037576674025
--197 AUROC: 0.5667491906303561
--197 AUPRC: 0.0828211165932433
--171 AUROC: 0.6517462422634837
--171 AUPRC: 0.13069801706328169
--277 AUROC: 0.6335168195718655
--277 AUPRC: 0.18788224508148677
--440 AUROC: 0.6621916877063508
--440 AUPRC: 0.08149545201834121
--400 AUROC: 0.6552871712292001
--400 AUPRC: 0.15795511245921828
--141 AUROC: 0.7753856881373661
--141 AUPRC: 0.245556182961389
--142 AUROC: 0.6600238017959537
--142 AUPRC: 0.09636118799074783
--444 AUROC: 0.6677363699102828
--444 AUPRC: 0.14430974859135823
--79 AUROC: 0.5688800792864221
--79 AUPRC: 0.05985131639662074
--227 AUROC: 0.6092241092241092
--227 AUPRC: 0.12534893371038539
--435 AUROC: 0.6234289617486339
--435 AUPRC: 0.09788201987164012
id: 122

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

122 AUROC: 0.5701163722476708
122 AUPRC: 0.1090565167707222
--73 AUROC: 0.6417408209074876
--73 AUPRC: 0.04126063624861136
--264 AUROC: 0.623520019693183
--264 AUPRC: 0.06168678787180708
--420 AUROC: 0.5985479898299697
--420 AUPRC: 0.1504438332574134
--338 AUROC: 0.5875604637627961
--338 AUPRC: 0.0724859378168459
--243 AUROC: 0.5917742012856184
--243 AUPRC: 0.03763732668361838
--458 AUROC: 0.5773603650693031
--458 AUPRC: 0.15469267666236325
--167 AUROC: 0.6341651403283238
--167 AUPRC: 0.10018359880197031
--300 AUROC: 0.6147480104472619
--300 AUPRC: 0.08682890369932476
--443 AUROC: 0.5920054963679126
--443 AUPRC: 0.09046050477485915
--188 AUROC: 0.5971519735608348
--188 AUPRC: 0.11682351168341168
--208 AUROC: 0.4747972137349047
--208 AUPRC: 0.06438634510791597
--252 AUROC: 0.6438061321596384
--252 AUPRC: 0.13179349550072358
--199 AUROC: 0.6183589385925825
--199 AUPRC: 0.12588731939654946
--176 AUROC: 0.5741162654139753
--176 AUPRC: 0.07768346255654188
--281 AUROC: 0.5845519656495266
--281 AUPRC: 0.050281965779096424
--411 AUROC: 0.6801459907030796
--411 AUPRC: 0.08909464216762752
--413 AUROC: 0.6491475602586714
--413 AUPRC: 0.07022271043483255
--449 AUROC: 0.6422103349416124
--449 AUPRC: 0.10918863792236955
--283 AUROC: 0.529188529591214
--283 AUPRC: 0.048651480785074974
--394 AUROC: 0.4480327023853841
--394 AUPRC: 0.057525323612643606
--307 AUROC: 0.6378051574737543
--307 AUPRC: 0.17404333686720785
--345 AUROC: 0.7103612761964342
--345 AUPRC: 0.14773634203718936
--148 AUROC: 0.6179501891283097
--148 AUPRC: 0.11344333452241545
--165 AUROC: 0.5965127451534505
--165 AUPRC: 0.07982979842741893
--417 AUROC: 0.6436725466115887
--417 AUPRC: 0.08546051425677569
--416 AUROC: 0.5903340757238307
--416 AUPRC: 0.06657283467554334
--331 AUROC: 0.6925489554355534
--331 AUPRC: 0.10238228617968947
--248 AUROC: 0.6020283579416887
--248 AUPRC: 0.09512565164193768
--183 AUROC: 0.6114354395604396
--183 AUPRC: 0.06656941572497795
--110 AUROC: 0.6320809040524005
--110 AUPRC: 0.1547876857069713
--365 AUROC: 0.626425
--365 AUPRC: 0.06086057166957339
--197 AUROC: 0.6185341986141834
--197 AUPRC: 0.0952019115901996
--171 AUROC: 0.7019783377541998
--171 AUPRC: 0.12328859538352797
--277 AUROC: 0.6057186544342508
--277 AUPRC: 0.08313064340367679
--440 AUROC: 0.5891192464556225
--440 AUPRC: 0.08187123268824334
--400 AUROC: 0.5433306494900698
--400 AUPRC: 0.10772523742121028
--141 AUROC: 0.7029402364972835
--141 AUPRC: 0.16769556169916047
--142 AUROC: 0.6000108189981608
--142 AUPRC: 0.09773578643514323
--444 AUROC: 0.6707384403036577
--444 AUPRC: 0.11643794216982456
--79 AUROC: 0.67077414381676
--79 AUPRC: 0.09353737643652414
--227 AUROC: 0.5918486275629133
--227 AUPRC: 0.13572006490765842
--435 AUROC: 0.6755009107468124
--435 AUPRC: 0.10710279890412205
id: 176

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(

176 AUROC: 0.5497044431395577
176 AUPRC: 0.06676709921202491
--73 AUROC: 0.6033189033189034
--73 AUPRC: 0.04692744954316813
--264 AUROC: 0.5231497468263546
--264 AUPRC: 0.06508982711302322
--420 AUROC: 0.5887533767678372
--420 AUPRC: 0.14454274111731363
--338 AUROC: 0.5056110854860405
--338 AUPRC: 0.048853822435882904
--243 AUROC: 0.3897450350187086
--243 AUPRC: 0.017321094685263244
--458 AUROC: 0.5429636673005706
--458 AUPRC: 0.12343586111821524
--167 AUROC: 0.5871961069839934
--167 AUPRC: 0.1072385308132234
--300 AUROC: 0.5773109656351376
--300 AUPRC: 0.13494373478991717
--443 AUROC: 0.4809713031189541
--443 AUPRC: 0.06698156294091798
--188 AUROC: 0.5418452515226708
--188 AUPRC: 0.07739178081455751
--208 AUROC: 0.5039443292594209
--208 AUPRC: 0.06017060195171911
--252 AUROC: 0.46729341382660244
--252 AUPRC: 0.07426814786249739
--199 AUROC: 0.5244719117086748
--199 AUPRC: 0.08822900269485358
--122 AUROC: 0.5721157104527713
--122 AUPRC: 0.11065399720479033
--281 AUROC: 0.5141132580156971
--281 AUPRC: 0.044184251764266935
--411 AUROC: 0.6042392988572536
--411 AUPRC: 0.07904526830296452
--413 AUROC: 0.4994855967078189
--413 AUPRC: 0.02202486266659706
--449 AUROC: 0.5539123138242081
--449 AUPRC: 0.11957571969518424
--283 AUROC: 0.5187797437461867
--283 AUPRC: 0.04851806873743312
--394 AUROC: 0.5055911915466338
--394 AUPRC: 0.08284211684609377
--307 AUROC: 0.5925158306948841
--307 AUPRC: 0.11726963330703134
--345 AUROC: 0.5136456052549264
--345 AUPRC: 0.07080949836195047
--148 AUROC: 0.5434995112414467
--148 AUPRC: 0.08048125978645843
--165 AUROC: 0.5664669643361782
--165 AUPRC: 0.06894874781198047
--417 AUROC: 0.5232150831751703
--417 AUPRC: 0.06358169165919914
--416 AUROC: 0.4664959168522643
--416 AUPRC: 0.03631132410013715
--331 AUROC: 0.5465826651393662
--331 AUPRC: 0.058585557850524626
--248 AUROC: 0.46307118787543344
--248 AUPRC: 0.06066701853488098
--183 AUROC: 0.5675529827315542
--183 AUPRC: 0.058978695040665455
--110 AUROC: 0.6000071978694308
--110 AUPRC: 0.15395028197328448
--365 AUROC: 0.49102500000000004
--365 AUPRC: 0.03531195334155682
--197 AUROC: 0.4648858092963977
--197 AUPRC: 0.06919794240003943
--171 AUROC: 0.5968906572354848
--171 AUPRC: 0.06652458358340593
--277 AUROC: 0.5790621814475025
--277 AUPRC: 0.09033986980420036
--440 AUROC: 0.48388036511944066
--440 AUPRC: 0.06869961105891129
--400 AUROC: 0.566411701556629
--400 AUPRC: 0.11875560223153897
--141 AUROC: 0.6187280281240013
--141 AUPRC: 0.13030644655700221
--142 AUROC: 0.5767607919506654
--142 AUPRC: 0.08550200405797298
--444 AUROC: 0.5716011042097998
--444 AUPRC: 0.12139219695871353
--79 AUROC: 0.5391696949675145
--79 AUPRC: 0.06623383674837954
--227 AUROC: 0.5260691689263117
--227 AUPRC: 0.1177121329883607
--435 AUROC: 0.4550318761384335
--435 AUPRC: 0.050456882125348004
id: 281

/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegressionCV was fitted without feature names
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/kara/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

KeyboardInterrupt:

In [ ]:
for p in os.listdir('./eicu-collaborative-research-database-demo-2.0.1/'):
    if not p.endswith('.csv.gz'):
        print(p)
        continue
    data_dir = './eicu-collaborative-research-database-demo-2.0.1/'
    df = pd.read_csv(f'{data_dir}/{p}')
    print(p)
    display(df.head())

diagnosis.csv.gz

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority
0,7607199,346380,False,5028,cardiovascular|ventricular disorders|hypertension,"401.9, I10",Other
1,7570429,346380,False,685,neurologic|altered mental status / pain|change...,"780.09, R41.82",Major
2,7705483,346380,True,5035,cardiovascular|shock / hypotension|hypotension,"458.9, I95.9",Major
3,7848601,346380,True,5035,neurologic|altered mental status / pain|schizo...,"295.90, F20.9",Major
4,7451475,346380,False,5028,pulmonary|disorders of vasculature|pulmonary e...,"415.19, I26.99",Major

vitalAperiodic.csv.gz

,vitalaperiodicid,patientunitstayid,observationoffset,noninvasivesystolic,noninvasivediastolic,noninvasivemean,paop,cardiacoutput,cardiacinput,svr,svri,pvr,pvri
0,3661418,141764,81,171.0,90.0,116.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3661424,141764,334,153.0,78.0,103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3661417,141764,77,176.0,87.0,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3661419,141764,165,173.0,106.0,128.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3661421,141764,255,182.0,103.0,133.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

admissionDx.csv.gz

,admissiondxid,patientunitstayid,admitdxenteredoffset,admitdxpath,admitdxname,admitdxtext
0,7351978,2900423,162,admission diagnosis|Non-operative Organ System...,Cardiovascular,Cardiovascular
1,7351977,2900423,162,admission diagnosis|Was the patient admitted f...,No,No
2,7351979,2900423,162,admission diagnosis|All Diagnosis|Non-operativ...,"Sepsis, pulmonary","Sepsis, pulmonary"
3,7745060,2902156,944,admission diagnosis|All Diagnosis|Non-operativ...,"Rhythm disturbance (atrial, supraventricular)","Rhythm disturbance (atrial, supraventricular)"
4,7745059,2902156,944,admission diagnosis|Non-operative Organ System...,Cardiovascular,Cardiovascular

respiratoryCare.csv.gz

,respcareid,patientunitstayid,respcarestatusoffset,currenthistoryseqnum,airwaytype,airwaysize,airwayposition,cuffpressure,ventstartoffset,ventendoffset,...,peeplimit,cpaplimit,setapneainterval,setapneatv,setapneaippeephigh,setapnearr,setapneapeakflow,setapneainsptime,setapneaie,setapneafio2
0,564013,147784,1188,2,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,564012,147784,-61,1,NaN,NaN,NaN,NaN,-361,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,545261,165840,-63,1,NaN,NaN,NaN,NaN,-363,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,545262,165840,73,2,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,550472,187150,7293,2,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

nurseAssessment.csv.gz

,nurseassessid,patientunitstayid,nurseassessoffset,nurseassessentryoffset,cellattributepath,celllabel,cellattribute,cellattributevalue
0,57436984,1054428,13791,13819,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Edema,Edema,generalized
1,57483728,1036759,4075,4076,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Secretions,Secretions,minimal
2,57483729,1036759,4075,4076,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Secretions,Secretions,thin
3,57483730,1036759,4075,4076,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Secretions,Secretions,clear
4,57505995,1054428,18051,18065,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Pacemaker/AICD,Pacemaker/AICD,NaN

hospital.csv.gz

   hospitalid numbedscategory teachingstatus   region
0          56            <100              f  Midwest
1          58       100 - 249              f  Midwest
2          59            <100              f  Midwest
3          60            <100              f  Midwest
4          61            <100              f  Midwest

vitalPeriodic.csv.gz

,vitalperiodicid,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,etco2,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3,icp
0,29524122,141765,1179,NaN,NaN,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29557845,141765,189,NaN,97.0,76.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29524442,141765,1169,NaN,NaN,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29513052,141765,1534,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29524600,141765,1164,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

carePlanGeneral.csv.gz

,cplgeneralid,patientunitstayid,activeupondischarge,cplitemoffset,cplgroup,cplitemvalue
0,3665765,174826,True,49,Ventilation,Spontaneous - adequate
1,3608330,174826,True,49,Care Limitation,Full therapy
2,3466711,174826,True,49,Stress Ulcer Prophylaxis,Proton pump inhibitor
3,3666045,174826,True,49,Airway,Not intubated/normal airway
4,3772790,174826,True,49,DVT Prophylaxis,Compression devices

patient.csv.gz

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
0,141764,129391,Female,87,Caucasian,59,91,NaN,157.5,23:36:00,...,ICU to SDU,2,stepdown/other,NaN,NaN,18:58:00,344,Home,Alive,002-1039
1,141765,129391,Female,87,Caucasian,59,91,"Rhythm disturbance (atrial, supraventricular)",157.5,23:36:00,...,Emergency Department,1,admit,46.5,45.0,13:14:00,2250,Step-Down Unit (SDU),Alive,002-1039
2,143870,131022,Male,76,Caucasian,68,103,"Endarterectomy, carotid",167.0,20:46:00,...,Operating Room,1,admit,77.5,79.4,10:00:00,793,Floor,Alive,002-12289
3,144815,131736,Female,34,Caucasian,56,82,"Overdose, other toxin, poison or drug",172.7,01:44:00,...,Emergency Department,1,admit,60.3,60.7,20:48:00,1121,Other External,Alive,002-1116
4,145427,132209,Male,61,Caucasian,68,103,"GI perforation/rupture, surgery for",177.8,23:48:00,...,Operating Room,1,admit,91.7,93.1,22:47:00,1369,Floor,Alive,002-12243

carePlanGoal.csv.gz

,cplgoalid,patientunitstayid,cplgoaloffset,cplgoalcategory,cplgoalvalue,cplgoalstatus,activeupondischarge
0,2287240,1318254,800,Infection/Labs,Normal electrolytes,Active,True
1,2287241,1318254,800,Infection/Labs,Absence of sepsis,Active,True
2,2287239,1318254,800,Infection/Labs,Stable Hgb and Hct,Active,True
3,2287237,1318254,800,Cardiovascular,Vital signs within normal parameters,Active,True
4,2370651,1318254,36,Cardiovascular,Vital signs within normal parameters,Active,False

sqlite
treatment.csv.gz

,treatmentid,patientunitstayid,treatmentoffset,treatmentstring,activeupondischarge
0,9579899,242895,838,cardiovascular|arrhythmias|anticoagulant admin...,False
1,8788989,242895,512,cardiovascular|consultations|Cardiology consul...,False
2,10293108,242895,838,cardiovascular|non-operative procedures|extern...,False
3,9017080,242895,70,pulmonary|vascular disorders|VTE prophylaxis|l...,False
4,9853526,242895,70,cardiovascular|consultations|Cardiology consul...,False

apacheApsVar.csv.gz

,apacheapsvarid,patientunitstayid,intubated,vent,dialysis,eyes,motor,verbal,meds,urine,...,ph,hematocrit,creatinine,albumin,pao2,pco2,bun,glucose,bilirubin,fio2
0,92788,141765,0,0,0,4,6,5,0,-1.0,...,-1.0,37.8,1.04,-1.0,-1.0,-1.0,28.0,61,-1.0,-1
1,8893,143870,0,0,0,4,6,5,0,-1.0,...,-1.0,34.1,1.14,-1.0,-1.0,-1.0,14.0,140,-1.0,-1
2,79585,144815,0,0,0,4,6,5,0,-1.0,...,-1.0,36.6,0.63,3.6,-1.0,-1.0,6.0,82,0.5,-1
3,203242,145427,0,0,0,4,6,5,0,-1.0,...,-1.0,40.4,1.05,-1.0,-1.0,-1.0,14.0,118,-1.0,-1
4,154681,147307,0,0,0,4,6,5,0,-1.0,...,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1

carePlanEOL.csv.gz

,cpleolid,patientunitstayid,cpleolsaveoffset,cpleoldiscussionoffset,activeupondischarge
0,11340,1054428,304,0,True
1,24686,1593179,3992,0,True
2,34322,2592641,3998,0,True
3,35600,2611237,303,0,True
4,35303,2621948,987,0,True

infusiondrug.csv.gz

,infusiondrugid,patientunitstayid,infusionoffset,drugname,drugrate,infusionrate,drugamount,volumeoffluid,patientweight
0,40215081,1461035,768,Volume (mL) Magnesium (ml/hr),25,NaN,NaN,NaN,NaN
1,38752780,1461035,648,Volume (mL) Magnesium (ml/hr),25,NaN,NaN,NaN,NaN
2,36960718,1461035,-1812,Volume (mL) Magnesium (ml/hr),25,NaN,NaN,NaN,NaN
3,38679313,1461035,-611,Volume (mL) Magnesium (ml/hr),25.42,NaN,NaN,NaN,NaN
4,40681648,1461035,828,Volume (mL) Magnesium (ml/hr),25,NaN,NaN,NaN,NaN

carePlanCareProvider.csv.gz

,cplcareprovderid,patientunitstayid,careprovidersaveoffset,providertype,specialty,interventioncategory,managingphysician,activeupondischarge
0,1124435,149713,11,NaN,family practice,I,Managing,True
1,1196330,157016,2,NaN,obstetrics/gynecology,I,Managing,True
2,1115508,165840,26,NaN,internal medicine,I,Managing,True
3,1153793,174826,49,NaN,critical care medicine (CCM),NaN,Managing,True
4,1135321,174956,3,NaN,cardiology,Unknown,Managing,True

microLab.csv.gz

,microlabid,patientunitstayid,culturetakenoffset,culturesite,organism,antibiotic,sensitivitylevel
0,840759,2597777,1343,"Sputum, Expectorated",mixed flora,NaN,NaN
1,840628,2597777,2723,"Sputum, Expectorated",mixed flora,NaN,NaN
2,833113,2608936,1,Bronchial Lavage,mixed flora,NaN,NaN
3,839342,2621338,22,"Sputum, Expectorated",gram negative rods,NaN,NaN
4,839341,2621338,22,"Sputum, Expectorated",gram positive cocci,NaN,NaN

nurseCare.csv.gz

,nursecareid,patientunitstayid,celllabel,nursecareoffset,nursecareentryoffset,cellattributepath,cellattribute,cellattributevalue
0,20977673,1014000,Hygiene/ADLs,2151,2138,flowsheet|Flowsheet Cell Labels|Nursing Care|H...,Hygiene/ADLs,ADLs assist
1,20977674,1014000,Hygiene/ADLs,2151,2138,flowsheet|Flowsheet Cell Labels|Nursing Care|H...,Hygiene/ADLs,oral care
2,21023628,1034813,Equipment,1680,1694,flowsheet|Flowsheet Cell Labels|Nursing Care|E...,Equipment,air mattress
3,21023629,1034813,Equipment,1680,1694,flowsheet|Flowsheet Cell Labels|Nursing Care|E...,Equipment,heels floated
4,21023630,1034813,Equipment,1680,1694,flowsheet|Flowsheet Cell Labels|Nursing Care|E...,Equipment,sling

physicalExam.csv.gz

,physicalexamid,patientunitstayid,physicalexamoffset,physicalexampath,physicalexamvalue,physicalexamtext
0,5276231,157427,1,notes/Progress Notes/Physical Exam/Physical Ex...,scored,scored
1,5276232,157427,1,notes/Progress Notes/Physical Exam/Physical Ex...,Performed - Structured,Performed - Structured
2,5276236,157427,1,notes/Progress Notes/Physical Exam/Physical Ex...,Admission,86.2
3,5276237,157427,1,notes/Progress Notes/Physical Exam/Physical Ex...,Current,86.2
4,5276238,157427,1,notes/Progress Notes/Physical Exam/Physical Ex...,Delta,0

respiratoryCharting.csv.gz

,respchartid,patientunitstayid,respchartoffset,respchartentryoffset,respcharttypecat,respchartvaluelabel,respchartvalue
0,107,184757,2922,2922,respFlowSettings,LPM O2,1
1,1108,187150,408,408,respFlowSettings,FiO2,80
2,10629,179269,117,117,respFlowSettings,LPM O2,6
3,13000,162502,3845,3845,respFlowSettings,LPM O2,25
4,13001,162502,3845,3845,respFlowSettings,FiO2,60

note.csv.gz

,noteid,patientunitstayid,noteoffset,noteenteredoffset,notetype,notepath,notevalue,notetext
0,3594780,157427,1,8,Comprehensive Progress,notes/Progress Notes/Admission Page One/Skip S...,Include Past Medical History,Include Past Medical History
1,3594785,157427,1,8,Comprehensive Progress,notes/Progress Notes/Assessment and Plan/View ...,System View,SystemView
2,3594786,157427,1,8,Comprehensive Progress,notes/Progress Notes/Assessment and Plan/Inclu...,Include Rx,Include Rx
3,3594787,157427,1,8,Comprehensive Progress,notes/Shared/View and Save/Save Options/Print/...,Copies,1
4,3595514,238463,19,22,Comprehensive Progress,notes/Progress Notes/Assessment and Plan/View ...,System View,SystemView

admissiondrug.csv.gz

,admissiondrugid,patientunitstayid,drugoffset,drugenteredoffset,drugnotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,drugdosage,drugunit,drugadmitfrequency,drughiclseqno
0,1373386,281479,420,444,Daily Progress,eCM Primary,THC Physician,False,True,NOVOLOG ...,0.0,,,20769
1,1917810,281479,24,31,Admission,eCM Primary,THC Nurse,True,True,NOVOLOG ...,0.0,,,20769
2,2118524,292154,242,243,Daily Progress,eCM Primary,Other,False,True,ALLOPURINOL ...,0.0,,,1100
3,1984925,292154,53,69,Admission,eCM Primary,THC Nurse,False,True,DILTIAZEM 24HR CD ...,0.0,,,182
4,2118526,292154,242,243,Daily Progress,eCM Primary,Other,False,True,CALCIUM CARBONATE ...,0.0,,,1163

lab.csv.gz

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
0,437880563,1754323,-647,3,Hct,38.30,38.3,%,%,-631
1,437880572,1754323,-647,3,platelets x 1000,181.00,181,K/mcL,k/mm cu,-631
2,437880560,1754323,-647,3,RBC,4.86,4.86,M/mcL,m/mm cu,-631
3,437880570,1754323,-647,3,-monos,8.70,8.7,%,%,-631
4,437880571,1754323,-647,3,MCHC,30.40,30.4,g/dL,%,-631

LICENSE.txt
apachePredVar.csv.gz

,apachepredvarid,patientunitstayid,sicuday,saps3day1,saps3today,saps3yesterday,gender,teachtype,region,bedcount,...,creatinine,dischargelocation,visitnumber,amilocation,day1meds,day1verbal,day1motor,day1eyes,day1pao2,day1fio2
0,4004,141765,1,0,0,0,1,0,3,12,...,1.04,4,1,-1,0,5,6,4,-1.0,-1
1,8047,143870,1,0,0,0,0,0,3,14,...,1.14,4,1,-1,0,5,6,4,-1.0,-1
2,1798882,144815,1,0,0,0,1,0,3,8,...,0.63,8,1,-1,0,5,6,4,-1.0,-1
3,1485310,145427,1,0,0,0,0,0,3,14,...,1.05,4,1,-1,0,5,6,4,-1.0,-1
4,27991,147307,1,0,0,0,1,0,3,43,...,-1.00,4,1,-1,0,5,6,4,-1.0,-1

customLab.csv.gz

,customlabid,patientunitstayid,labotheroffset,labothertypeid,labothername,labotherresult,labothervaluetext
0,25451,243999,45,1,Creatinine w Est GFR,51.0,51
1,25450,243999,450,1,GFR,NaN,>60
2,24747,267829,202,1,Vitamin B12,NaN,>1000
3,24653,267829,202,1,Iron,NaN,<10.0
4,24748,267829,202,1,Folate,NaN,>20.0

apachePatientResult.csv.gz

,apachepatientresultsid,patientunitstayid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,apacheversion,predictedicumortality,actualicumortality,predictediculos,...,predictedhospitallos,actualhospitallos,preopmi,preopcardiaccath,ptcawithin24h,unabridgedunitlos,unabridgedhosplos,actualventdays,predventdays,unabridgedactualventdays
0,31917,141765,hospitalist,Unknown,23,47,IV,0.008247,ALIVE,0.722231,...,2.881710,1.8222,0,0,0,1.5625,1.8222,NaN,NaN,NaN
1,31918,141765,hospitalist,Unknown,23,47,IVa,0.012311,ALIVE,1.374807,...,3.173925,1.8222,0,0,0,1.5625,1.8222,NaN,NaN,NaN
2,21398,143870,family practice,Unknown,43,60,IVa,0.015707,ALIVE,3.021671,...,6.032627,0.8465,0,0,0,0.5506,0.8465,NaN,NaN,NaN
3,21397,143870,family practice,Unknown,43,60,IV,0.017739,ALIVE,3.006522,...,5.955292,0.8465,0,0,0,0.5506,0.8465,NaN,NaN,NaN
4,181,144815,internal medicine,I,25,25,IV,0.001834,ALIVE,0.592446,...,2.196294,0.8063,0,0,0,0.7784,0.8063,NaN,NaN,NaN

carePlanInfectiousDisease.csv.gz

,cplinfectid,patientunitstayid,activeupondischarge,cplinfectdiseaseoffset,infectdiseasesite,infectdiseaseassessment,responsetotherapy,treatment
0,3329,249328,True,1153,Urinary tract,Definite infection,NaN,NaN
1,3234,260860,False,1451,Urinary tract,Definite infection,NaN,NaN
2,1149,260860,True,2866,Urinary tract,Definite infection,NaN,NaN
3,255,260860,False,1451,Skin & Soft tissue,Definite infection,NaN,NaN
4,328,260860,True,2866,Skin & Soft tissue,Definite infection,NaN,NaN

SHA256SUMS.txt
allergy.csv.gz

,allergyid,patientunitstayid,allergyoffset,allergyenteredoffset,allergynotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,allergytype,allergyname,drughiclseqno
0,357144,243097,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,NaN,Non Drug,penicillins,NaN
1,442253,243097,1288,1294,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721.0
2,357143,243097,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721.0
3,329929,243097,21,28,Admission,eCM Primary,THC Nurse,True,True,NaN,Non Drug,penicillins,NaN
4,363374,243097,3988,3989,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721.0

nurseCharting.csv.gz

,nursingchartid,patientunitstayid,nursingchartoffset,nursingchartentryoffset,nursingchartcelltypecat,nursingchartcelltypevallabel,nursingchartcelltypevalname,nursingchartvalue
0,189336686,143870,-67,-67,Other Vital Signs and Infusions,"Eye, Ear, Nose, Throat Assessment",Value,WDL
1,187848155,143870,239,239,Other Vital Signs and Infusions,Gastrointestinal Assessment,Value,X
2,281610014,143870,433,433,Other Vital Signs and Infusions,Pain Assessment,Value,WDL
3,237860915,143870,433,433,Other Vital Signs and Infusions,Neurological Assessment,Value,WDL
4,265486190,143870,1108,1108,Vital Signs,Respiratory Rate,Respiratory Rate,15

pastHistory.csv.gz

,pasthistoryid,patientunitstayid,pasthistoryoffset,pasthistoryenteredoffset,pasthistorynotetype,pasthistorypath,pasthistoryvalue,pasthistoryvaluetext
0,990803,141765,7,12,Comprehensive Progress,notes/Progress Notes/Past History/Past History...,No Health Problems,NoHealthProblems
1,970059,143870,4,10,Comprehensive Progress,notes/Progress Notes/Past History/Past History...,No Health Problems,NoHealthProblems
2,1180401,144815,32,41,Comprehensive Progress,notes/Progress Notes/Past History/Past History...,No Health Problems,NoHealthProblems
3,1194998,145427,8,13,Comprehensive Progress,notes/Progress Notes/Past History/Past History...,No Health Problems,NoHealthProblems
4,896652,147307,53,56,Comprehensive Progress,notes/Progress Notes/Past History/Past History...,No Health Problems,NoHealthProblems

medication.csv.gz

/var/folders/gv/cvbvg4412fg914zd3_cc80lh0000gn/T/ipykernel_22833/313154529.py:6: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'{data_dir}/{p}')

,medicationid,patientunitstayid,drugorderoffset,drugstartoffset,drugivadmixture,drugordercancelled,drugname,drughiclseqno,dosage,routeadmin,frequency,loadingdose,prn,drugstopoffset,gtc
0,7278819,141765,134,1396,No,No,WARFARIN SODIUM 5 MG PO TABS,2812.0,5 3,PO,NaN,NaN,No,2739,0
1,9726266,141765,1,-188,No,No,5 ML VIAL : DILTIAZEM HCL 25 MG/5ML IV SOLN,182.0,15 3,IV,Once PRN,NaN,Yes,171,38
2,10293599,141765,115,856,No,No,ASPIRIN EC 81 MG PO TBEC,1820.0,81 3,PO,Daily,NaN,No,2739,0
3,10871534,141765,114,316,No,No,DILTIAZEM HCL 30 MG PO TABS,182.0,30 3,PO,Q6H SCH,NaN,No,2739,0
4,10128716,141765,115,856,No,No,LISINOPRIL 5 MG PO TABS,132.0,5 3,PO,Daily,NaN,No,2428,0

intakeOutput.csv.gz

,intakeoutputid,patientunitstayid,intakeoutputoffset,intaketotal,outputtotal,dialysistotal,nettotal,intakeoutputentryoffset,cellpath,celllabel,cellvaluenumeric,cellvaluetext
0,9314532,147307,-394,0.0,0.0,0.0,0.0,-394,flowsheet|Flowsheet Cell Labels|I&O|Weight|Bod...,Bodyweight (lb),159.8,159.8
1,9314533,147307,-394,0.0,0.0,0.0,0.0,-394,flowsheet|Flowsheet Cell Labels|I&O|Weight|Bod...,Bodyweight (kg),72.5,72.5
2,9319306,211715,1533,120.0,0.0,0.0,120.0,1533,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,P.O.,120.0,120.0
3,9319891,219981,6504,120.0,0.0,0.0,120.0,6504,flowsheet|Flowsheet Cell Labels|I&O|Intake (ml...,P.O.,120.0,120.0
4,9319987,158057,624,0.0,0.0,0.0,0.0,624,flowsheet|Flowsheet Cell Labels|I&O|Weight|Bod...,Bodyweight (lb),359.0,359.0

### apache table

In [ ]:
df = pd.read_csv(f'{data_dir}/apachePatientResult.csv.gz').drop(columns='apachepatientresultsid')
df = df[df.patientunitstayid.isin(patient.patientunitstayid.unique())]
df = patient[['patientunitstayid', 'patienthealthsystemstayid', 'mortality_at48h']].merge(df, on=['patientunitstayid'], how='left')
df = df[df.apacheversion=='IVa']
apache_ypred = df.groupby('patienthealthsystemstayid')[['predictedicumortality']].mean().reset_index()
display(df)

,patientunitstayid,patienthealthsystemstayid,mortality_at48h,apachepatientresultsid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,apacheversion,predictedicumortality,actualicumortality,predictediculos,actualiculos,predictedhospitalmortality,actualhospitalmortality,predictedhospitallos,actualhospitallos,preopmi,preopcardiaccath,ptcawithin24h,unabridgedunitlos,unabridgedhosplos,actualventdays,predventdays,unabridgedactualventdays
1,141168,128919,1,26571.0,critical care medicine (CCM),Unknown,49.0,65.0,IVa,0.028889,EXPIRED,3.091127,2.4972,0.059099,EXPIRED,6.628720,2.4972,0.0,0.0,0.0,2.4972,2.4972,NaN,NaN,NaN
5,141194,128941,0,53136.0,critical care medicine (CCM),Unknown,57.0,70.0,IVa,0.046448,ALIVE,4.167129,3.3423,0.102283,ALIVE,12.978228,9.2167,0.0,0.0,0.0,3.3423,9.2167,NaN,NaN,NaN
8,141203,128948,0,8.0,hospitalist,I,73.0,90.0,IVa,0.291609,ALIVE,8.670299,1.2979,0.470973,ALIVE,16.319389,3.7493,0.0,0.0,0.0,1.2979,3.7493,2.0,5.738093,2.0
10,141227,128968,0,138142.0,internal medicine,Unknown,83.0,100.0,IVa,0.335934,ALIVE,8.209624,1.1472,0.488562,ALIVE,16.508280,1.8861,0.0,0.0,0.0,1.1472,1.8861,2.0,4.474474,2.0
13,141233,128973,0,47819.0,surgery-cardiac,I,49.0,66.0,IVa,0.027697,ALIVE,3.107540,10.8923,0.035490,ALIVE,6.739768,15.9313,0.0,0.0,0.0,10.8923,15.9313,2.0,1.422043,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263924,3353235,2743084,0,3267489.0,cardiology,II,30.0,35.0,IVa,0.011009,ALIVE,1.934817,0.7423,0.022630,ALIVE,5.759009,2.6701,0.0,0.0,0.0,0.7423,2.6701,NaN,NaN,NaN
263926,3353237,2743086,0,3246235.0,pulmonary/CCM,II,37.0,54.0,IVa,0.026984,ALIVE,2.566297,0.8812,0.062568,ALIVE,7.565244,6.7215,0.0,0.0,0.0,0.8812,6.7215,NaN,NaN,NaN
263928,3353251,2743099,0,3272802.0,cardiology,II,142.0,158.0,IVa,0.876797,ALIVE,8.920949,11.2909,0.918169,ALIVE,11.222566,13.4056,0.0,0.0,1.0,11.2909,13.4056,9.0,6.464630,9.0
263930,3353254,2743102,0,3262174.0,hospitalist,II,18.0,35.0,IVa,0.011004,ALIVE,2.045046,0.2993,0.025801,ALIVE,6.199350,4.4549,0.0,0.0,0.0,0.2993,4.4549,NaN,NaN,NaN
263931,3353263,2743110,0,3246241.0,nephrology,II,22.0,22.0,IVa,0.006508,ALIVE,1.754389,0.6444,0.012324,ALIVE,6.260686,6.7347,0.0,0.0,0.0,0.6444,6.7347,NaN,NaN,NaN

In [ ]:
lab = pd.read_csv(f'{data_dir}/apachePredVar.csv.gz')
lab = lab[lab.patientunitstayid.isin(patient.patientunitstayid.unique())]
lab = lab.merge(patient[['patientunitstayid', 'patienthealthsystemstayid']], on=['patientunitstayid'], how='left')
display(lab)
lab.patienthealthsystemstayid.nunique()

,apachepredvarid,patientunitstayid,sicuday,saps3day1,saps3today,saps3yesterday,gender,teachtype,region,bedcount,admitsource,graftcount,meds,verbal,motor,eyes,age,admitdiagnosis,thrombolytics,diedinhospital,aids,hepaticfailure,lymphoma,metastaticcancer,leukemia,immunosuppression,cirrhosis,electivesurgery,activetx,readmit,ima,midur,ventday1,oobventday1,oobintubday1,diabetes,managementsystem,var03hspxlos,pao2,fio2,ejectfx,creatinine,dischargelocation,visitnumber,amilocation,day1meds,day1verbal,day1motor,day1eyes,day1pao2,day1fio2,patienthealthsystemstayid
0,2406430,141178,1,0,0,0,1,0,3,9,8,3,-1,-1,-1,-1,52.0,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,-1.00,4,1,-1,-1,-1,-1,-1,-1.0,-1.0,128927
1,27799,141197,1,0,0,0,0,0,3,30,8,3,0,5,6,4,71.0,SEPSISPULM,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,-1.00,4,1,-1,0,5,6,4,-1.0,-1.0,128943
2,1786953,141227,1,0,0,0,0,0,3,9,4,3,0,4,6,3,82.0,SEPSISPULM,0,0,0,0,0,0,0,0,0,NaN,1,0,0,0,1,1,0,0,1,0,65.0,21.0,-1,1.90,6,1,-1,0,4,6,3,65.0,21.0,128968
3,7948,141229,1,0,0,0,1,0,3,43,8,3,0,5,6,4,NaN,CHF,0,0,0,0,0,0,0,0,0,NaN,1,0,0,0,1,1,0,0,1,0,-1.0,-1.0,-1,-1.00,4,1,-1,0,5,6,4,-1.0,-1.0,128970
4,11916,141260,1,0,0,0,1,0,3,19,8,3,0,5,6,4,43.0,ASTHMA,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,1.04,4,1,-1,0,5,6,4,-1.0,-1.0,128995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64268,1806800,3353184,1,0,0,0,1,0,3,23,8,3,0,5,6,4,83.0,CARDIOMYOP,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,0.63,8,1,-1,0,5,6,4,-1.0,-1.0,2743043
64269,825962,3353235,1,0,0,0,0,0,3,23,8,3,0,5,6,4,50.0,CHF,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,-1.00,8,1,-1,0,5,6,4,-1.0,-1.0,2743084
64270,996721,3353237,1,0,0,0,1,0,3,11,7,3,0,4,6,4,79.0,PULMEMBOL,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,1.07,4,1,-1,0,4,6,4,-1.0,-1.0,2743086
64271,2418339,3353254,1,0,0,0,0,0,3,14,8,3,0,5,6,4,81.0,LOWGIBLEED,0,0,0,0,0,0,0,0,0,NaN,1,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,-1.00,4,1,-1,0,5,6,4,-1.0,-1.0,2743102
64272,1501038,3353263,1,0,0,0,0,0,3,11,8,3,0,5,6,4,35.0,PULMEMBOL,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,-1.0,-1.0,-1,-1.00,8,1,-1,0,5,6,4,-1.0,-1.0,2743110

63855

In [ ]:
lab.replace(-1, np.nan)

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset,hospitaladmitoffset,time_from_admit
1,50363251,141168,1133.0,3,pt - inr,2.5,2.5,ratio,NaN,1208.0,0.0,1133.0
3,50363250,141168,1133.0,3,pt,26.6,26.6,sec,sec,1208.0,0.0,1133.0
5,56072056,141168,231.0,3,pt - inr,1.7,1.7,ratio,NaN,268.0,0.0,231.0
8,47753731,141168,516.0,1,bun,26.0,26,mg/dL,mg/dL,540.0,0.0,516.0
11,56072055,141168,231.0,3,pt,17.1,17.1,sec,sec,268.0,0.0,231.0
...,...,...,...,...,...,...,...,...,...,...,...,...
28417385,826336611,3353263,-37.0,3,ptt,25.0,25,sec,sec,54.0,-108.0,71.0
28417387,824772677,3353263,-7.0,3,mch,27.0,27,pg,pg,6.0,-108.0,101.0
28417389,824772676,3353263,-7.0,3,rdw,13.3,13.3,%,%,6.0,-108.0,101.0
28417391,824772675,3353263,-7.0,3,wbc x 1000,6.4,6.4,K/mcL,K/uL,6.0,-108.0,101.0
28417393,824772678,3353263,-7.0,3,-monos,10.0,10,%,%,6.0,-108.0,101.0

In [ ]:
lab = pd.read_csv(f'{data_dir}/apachePredVar.csv.gz').drop(columns='apachepredvarid').replace(-1, np.nan)
# lab = pd.read_csv(f'{data_dir}/apacheApsVar.csv.gz').drop(columns='apacheapsvarid').replace(-1, np.nan)
lab = lab[lab.patientunitstayid.isin(patient.patientunitstayid.unique())]
# lab["labname"] = lab["labname"].str.lower().replace("-",'').replace(' ', '')
# lab = lab.merge(patient[['patientunitstayid', 'hospitaladmitoffset']], on='patientunitstayid', how='left')
# lab['time_from_admit'] = - lab.hospitaladmitoffset + lab.labresultoffset
# lab = lab[lab.time_from_admit <= hours_for_data*60]
print(lab.columns)
lab

Index(['patientunitstayid', 'sicuday', 'saps3day1', 'saps3today',
       'saps3yesterday', 'gender', 'teachtype', 'region', 'bedcount',
       'admitsource', 'graftcount', 'meds', 'verbal', 'motor', 'eyes', 'age',
       'admitdiagnosis', 'thrombolytics', 'diedinhospital', 'aids',
       'hepaticfailure', 'lymphoma', 'metastaticcancer', 'leukemia',
       'immunosuppression', 'cirrhosis', 'electivesurgery', 'activetx',
       'readmit', 'ima', 'midur', 'ventday1', 'oobventday1', 'oobintubday1',
       'diabetes', 'managementsystem', 'var03hspxlos', 'pao2', 'fio2',
       'ejectfx', 'creatinine', 'dischargelocation', 'visitnumber',
       'amilocation', 'day1meds', 'day1verbal', 'day1motor', 'day1eyes',
       'day1pao2', 'day1fio2'],
      dtype='object')

,patientunitstayid,sicuday,saps3day1,saps3today,saps3yesterday,gender,teachtype,region,bedcount,admitsource,graftcount,meds,verbal,motor,eyes,age,admitdiagnosis,thrombolytics,diedinhospital,aids,hepaticfailure,lymphoma,metastaticcancer,leukemia,immunosuppression,cirrhosis,electivesurgery,activetx,readmit,ima,midur,ventday1,oobventday1,oobintubday1,diabetes,managementsystem,var03hspxlos,pao2,fio2,ejectfx,creatinine,dischargelocation,visitnumber,amilocation,day1meds,day1verbal,day1motor,day1eyes,day1pao2,day1fio2
1,141178,1,0,0,0,1.0,0,3,9,8.0,3,NaN,NaN,NaN,NaN,52.0,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,4.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,141197,1,0,0,0,0.0,0,3,30,8.0,3,0.0,5.0,6.0,4.0,71.0,SEPSISPULM,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,4.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN
6,141227,1,0,0,0,0.0,0,3,9,4.0,3,0.0,4.0,6.0,3.0,82.0,SEPSISPULM,0,0,0,0,0,0,0,0,0,NaN,1,0,0,0,1,1,0,0,1,0,65.0,21.0,NaN,1.90,6.0,1,NaN,0.0,4.0,6.0,3.0,65.0,21.0
7,141229,1,0,0,0,1.0,0,3,43,8.0,3,0.0,5.0,6.0,4.0,NaN,CHF,0,0,0,0,0,0,0,0,0,NaN,1,0,0,0,1,1,0,0,1,0,NaN,NaN,NaN,NaN,4.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN
10,141260,1,0,0,0,1.0,0,3,19,8.0,3,0.0,5.0,6.0,4.0,43.0,ASTHMA,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,1.04,4.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171161,3353184,1,0,0,0,1.0,0,3,23,8.0,3,0.0,5.0,6.0,4.0,83.0,CARDIOMYOP,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0.63,8.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN
171172,3353235,1,0,0,0,0.0,0,3,23,8.0,3,0.0,5.0,6.0,4.0,50.0,CHF,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,8.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN
171173,3353237,1,0,0,0,1.0,0,3,11,7.0,3,0.0,4.0,6.0,4.0,79.0,PULMEMBOL,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,1.07,4.0,1,NaN,0.0,4.0,6.0,4.0,NaN,NaN
171175,3353254,1,0,0,0,0.0,0,3,14,8.0,3,0.0,5.0,6.0,4.0,81.0,LOWGIBLEED,0,0,0,0,0,0,0,0,0,NaN,1,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,4.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN
171176,3353263,1,0,0,0,0.0,0,3,11,8.0,3,0.0,5.0,6.0,4.0,35.0,PULMEMBOL,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,8.0,1,NaN,0.0,5.0,6.0,4.0,NaN,NaN

In [ ]:
patient.hospitalid.value_counts(dropna=False)

hospitalid
146    40
123    30
171    25
157    25
167    24
       ..
408    10
384    10
383    10
397    10
259    10
Name: count, Length: 186, dtype: int64

In [ ]:
patient.ethnicity.value_counts(dropna=False)

ethnicity
Caucasian           2010
African American     231
Hispanic             115
Other/Unknown         83
NaN                   39
Asian                 30
Native American       12
Name: count, dtype: int64

In [ ]:
# Create a database connection using settings from config file
config='../db/config.ini'

# connection info
conn_info = dict()
if os.path.isfile(config):
    config = ConfigObj(config)
    conn_info["sqluser"] = config['username']
    conn_info["sqlpass"] = config['password']
    conn_info["sqlhost"] = config['host']
    conn_info["sqlport"] = config['port']
    conn_info["dbname"] = config['dbname']
    conn_info["schema_name"] = config['schema_name']
else:
    conn_info["sqluser"] = 'postgres'
    conn_info["sqlpass"] = ''
    conn_info["sqlhost"] = 'localhost'
    conn_info["sqlport"] = 5432
    conn_info["dbname"] = 'eicu'
    conn_info["schema_name"] = 'public,eicu_crd'
    
# Connect to the eICU database
print('Database: {}'.format(conn_info['dbname']))
print('Username: {}'.format(conn_info["sqluser"]))
if conn_info["sqlpass"] == '':
    # try connecting without password, i.e. peer or OS authentication
    try:
        if (conn_info["sqlhost"] == 'localhost') & (conn_info["sqlport"]=='5432'):
            con = psycopg2.connect(dbname=conn_info["dbname"],
                                   user=conn_info["sqluser"])            
        else:
            con = psycopg2.connect(dbname=conn_info["dbname"],
                                   host=conn_info["sqlhost"],
                                   port=conn_info["sqlport"],
                                   user=conn_info["sqluser"])
    except:
        conn_info["sqlpass"] = getpass.getpass('Password: ')

        con = psycopg2.connect(dbname=conn_info["dbname"],
                               host=conn_info["sqlhost"],
                               port=conn_info["sqlport"],
                               user=conn_info["sqluser"],
                               password=conn_info["sqlpass"])
query_schema = 'set search_path to ' + conn_info['schema_name'] + ';'

Database: eicu
Username: postgres

NameError: name 'getpass' is not defined

In [ ]:
conda create --name cs197-rag python=3.12